export const COUNTRY_CODES: { name: string; dial: string }[] = [
  { name: "Nigeria", dial: "+234" },
  { name: "United States", dial: "+1" },
  { name: "United Kingdom", dial: "+44" },
  { name: "Spain", dial: "+34" },
  { name: "Ghana", dial: "+233" },
  { name: "Kenya", dial: "+254" },
  { name: "South Africa", dial: "+27" },
  { name: "Egypt", dial: "+20" },
  { name: "Canada", dial: "+1" },
  { name: "Ireland", dial: "+353" },
  { name: "Germany", dial: "+49" },
  { name: "France", dial: "+33" },
  { name: "Italy", dial: "+39" },
  { name: "Portugal", dial: "+351" },
  { name: "Netherlands", dial: "+31" },
  { name: "Belgium", dial: "+32" },
  { name: "Switzerland", dial: "+41" },
  { name: "Sweden", dial: "+46" },
  { name: "Norway", dial: "+47" },
  { name: "Denmark", dial: "+45" },
  { name: "Poland", dial: "+48" },
  { name: "United Arab Emirates", dial: "+971" },
  { name: "Saudi Arabia", dial: "+966" },
  { name: "India", dial: "+91" },
  { name: "Pakistan", dial: "+92" },
  { name: "China", dial: "+86" },
  { name: "Japan", dial: "+81" },
  { name: "South Korea", dial: "+82" },
  { name: "Singapore", dial: "+65" },
  { name: "Australia", dial: "+61" },
  { name: "New Zealand", dial: "+64" },
  { name: "Brazil", dial: "+55" },
  { name: "Mexico", dial: "+52" },
  { name: "Argentina", dial: "+54" },
  { name: "Cameroon", dial: "+237" },
  { name: "Côte d'Ivoire", dial: "+225" },
  { name: "Senegal", dial: "+221" },
  { name: "Ethiopia", dial: "+251" },
  { name: "Morocco", dial: "+212" },
  { name: "Rwanda", dial: "+250" },
  { name: "Uganda", dial: "+256" },
  { name: "Tanzania", dial: "+255" },
  { name: "Other", dial: "" },
];
