/* eslint-disable */
// Ported from the Claude Design handoff (projects.js). Imported by the case study page (server) and the Experience/Case Study (client).
// Shared project data for Case Study + Experience. Results stay factual: no invented metrics.
export const ZB_PROJECTS = [
  { id: 'malaak', name: 'MALAAK', cat: 'Modest Fashion', year: '2026', img: '/zb/assets/a3eb67a33eb96ed907adcdd7619cb9d5.jpg', url: 'https://malaak-abaya.vercel.app/',
    desc: 'Minimal editorial fashion site with a hover-reveal product grid and WhatsApp ordering, built for Snapchat-native buyers.',
    challenge: 'A modest luxury abaya label selling mostly through Snapchat DMs, with no single place to see the collection.',
    approach: 'Treat the site like a lookbook: quiet split-hero layout, big imagery, and ordering that stays inside the channel customers already use.',
    product: 'An editorial storefront with a hover-reveal product grid and one-tap WhatsApp ordering per piece.',
    experience: 'Slow, calm motion and generous whitespace so the garments carry the page.',
    result: 'Live, and the collection now has one link to share.', tags: ['Fashion', 'Editorial', 'WhatsApp'] },
  { id: 'doberman', name: 'DOBERMAN', cat: 'Brand', year: '2026', img: '/zb/assets/b78ad4f230a4015d24a420fce2a7d53b.jpg', url: 'https://doberman-kappa.vercel.app/',
    desc: 'High-impact brand site. Aggressive typography, a dramatic dark palette and a conversion-focused layout.',
    challenge: 'A bold brand that needed a site as loud as its identity without losing the path to action.',
    approach: 'Lead with type. Oversized, aggressive headlines on a dark palette, with every section pointing at one conversion.',
    product: 'A single-page brand experience with interactive sections and a clear call to action.',
    experience: 'Hard cuts, heavy weight and contrast. It commands attention.',
    result: 'Live brand site with a direct conversion flow.', tags: ['Brand', 'Dark', 'Interactive'] },
  { id: 'thisorthat', name: 'THIS OR THAT', cat: 'Product', year: '2026', img: '/zb/assets/thisorthat-icon.png', logo: true, url: 'https://this-or-that-fawn-rho.vercel.app/',
    desc: 'A quick-fire decision product: two options, one tap, and you see what everyone else picked.',
    challenge: 'Turn a simple “this or that” game into a product people come back to.',
    approach: 'Strip it to the core loop: two choices, one tap, instant results. Nothing between the user and the next question.',
    product: 'A fast web app with head-to-head choices and live results after every vote.',
    experience: 'Snappy transitions and immediate feedback so each tap feels rewarding.',
    result: 'Live product built and shipped by Zebraish Studio.', tags: ['Product', 'Web app', 'Social'] },
  { id: 'aaura', name: 'AAURA', cat: 'Fragrance', year: '2026', img: '/zb/assets/ae7685b3f6993315e423325f7889a7f4.jpg', url: 'https://aaura-perfume.vercel.app/',
    desc: 'Arabian luxury perfumery. Animated gold particle field, arabesque typography and WhatsApp ordering.',
    challenge: 'Sell scent online, where the product itself cannot be experienced.',
    approach: 'Sell the feeling instead: an animated gold particle field, arabesque type and a rich, warm palette.',
    product: 'A luxury storefront with canvas effects and WhatsApp ordering.',
    experience: 'Every pixel reads as expensive: drifting gold, deep blacks, slow reveals.',
    result: 'Live luxury storefront taking orders over WhatsApp.', tags: ['Luxury', 'Canvas FX', 'Arabic'] },
  { id: 'prieto', name: 'Christian Prieto', cat: 'Creator', year: '2026', serif: true, url: 'https://christain-theapeacademys-projects.vercel.app/',
    desc: 'Creator portfolio for a Barcelona-based fashion and lifestyle creator. Stats-forward, TikTok-native, with a brand collab flow.',
    challenge: 'A creator with a big audience (9.6M likes) and no professional page for brands to land on.',
    approach: 'Make the numbers the hero and speak the language of the platform the audience lives on.',
    product: 'A stats-forward portfolio with a direct brand collaboration flow.',
    experience: 'TikTok-native pacing: bold, quick and scroll-friendly.',
    result: 'Live creator page for brand partnerships.', tags: ['Creator', 'Fashion', 'TikTok'] },
  { id: 'mfm', name: 'MFM', cat: 'Children’s Ministry', year: '2026', img: '/zb/assets/mfm-logo.png', logo: true, url: 'https://cct-rho.vercel.app/',
    desc: 'Website for the MFM children’s ministry.',
    challenge: 'Give a children’s ministry a clear, friendly home online for parents and volunteers.',
    approach: 'Warm, simple and easy to navigate, with the essentials one tap away.',
    product: 'A ministry website with programmes, information and contact.',
    experience: 'Friendly and uncluttered, built for parents on their phones.',
    result: 'Live ministry website.', tags: ['Community', 'Ministry', 'Mobile-first'] },
  { id: 'ape', name: 'APE ACADEMY', cat: 'Education', year: '2026', img: '/zb/assets/Screenshot_20260412-220250_Chrome.png', url: 'https://deploy-1-p1ke.vercel.app/',
    desc: 'Bold educational platform with a strong identity, structured content and a no-nonsense conversion flow.',
    challenge: 'An education brand that needed to look serious to serious learners.',
    approach: 'A strong identity, structured content and one clear route to enrol.',
    product: 'An educational platform with a dark, bold theme and a direct conversion flow.',
    experience: 'Confident and structured. No distractions from the offer.',
    result: 'Live education platform.', tags: ['Education', 'Dark', 'Bold'] },
  { id: 'hotchef', name: 'HOT CHEF', cat: 'Food & Drink', year: '2026', url: 'https://hot-chef.vercel.app/',
    desc: 'A Nigerian kitchen where customers browse the menu and order food online.',
    challenge: 'A Nigerian kitchen taking orders by phone and chat, with no menu customers could browse.',
    approach: 'Put the food first: appetising dishes, clear prices and ordering in as few taps as possible.',
    product: 'An online menu and ordering experience for Nigerian dishes.',
    experience: 'Warm, hungry-making and fast on mobile.',
    result: 'Live, with customers ordering food online.', tags: ['Food', 'Ordering', 'Nigerian'] },
  { id: 'reverie', name: 'REVERIE', cat: 'Beauty', year: '2026', img: '/zb/assets/4c7faa2cf965371c0d8c790e9d5f61a1.jpg', url: 'https://reverie-salon.vercel.app/',
    desc: 'Soft marble luxury salon site. Services grid, team showcase and WhatsApp booking.',
    challenge: 'A luxury salon booked mostly by word of mouth, with no way to show services and team.',
    approach: 'Soft marble luxury: calm, premium and easy to book.',
    product: 'Services grid, team showcase and WhatsApp booking.',
    experience: 'Soft, light and considered, like the salon itself.',
    result: 'Live salon site with WhatsApp booking.', tags: ['Beauty', 'Marble', 'Booking'] },
];

if (typeof window !== "undefined") window.ZB_PROJECTS = ZB_PROJECTS;
