// Generates SQL seed batches for public.catalogue_project_types/steps/options
// from the real apps/studio/lib/catalogue/{catalogue,shared}.ts source — used
// to build Phase 7's initial catalogue_versions row (and to regenerate a
// fresh seed if the static catalogue changes before the dual-read cutover
// lands). All ids are client-generated UUIDs, so every statement is
// self-contained (no RETURNING/session-variable chaining needed) and safe to
// apply in any number of separate batches.
// Run with: npx tsx scripts/gen-catalogue-seed.ts <output-dir>
import { PROJECT_TYPES, FLOWS, FLAT_BASE_PRICES } from "../apps/studio/lib/catalogue/catalogue";
import { writeFileSync, mkdirSync } from "node:fs";
import { randomUUID } from "node:crypto";

function sqlStr(v: string | null | undefined): string {
  if (v === null || v === undefined) return "null";
  return `'${v.replace(/'/g, "''")}'`;
}
function sqlNum(v: number | null | undefined): string {
  if (v === null || v === undefined) return "null";
  return String(v);
}
function sqlBool(v: boolean | null | undefined): string {
  return v ? "true" : "false";
}

const outDir = process.argv[2] ?? "/tmp/catalogue-seed";
mkdirSync(outDir, { recursive: true });

const versionId = randomUUID();

const header = `-- Auto-generated by scripts/gen-catalogue-seed.ts from
-- apps/studio/lib/catalogue/{catalogue,shared}.ts — do not hand-edit.
`;

writeFileSync(
  `${outDir}/00_version.sql`,
  header +
    `insert into public.catalogue_versions (id, version_number, is_active, published_at, created_by, notes)
values (${sqlStr(versionId)}, 1, true, now(), 'system-seed', 'Initial version — mirrors the live catalogue.ts/shared.ts at Phase 7 build time.');
`,
);

PROJECT_TYPES.forEach((pt, typeOrder) => {
  const flow = FLOWS[pt.flow];
  if (!flow) throw new Error(`No flow for project type ${pt.id}`);
  const basePrice = FLAT_BASE_PRICES[pt.id];

  const lines: string[] = [header];

  lines.push(`insert into public.catalogue_project_types (version_id, type_id, label, helper, type_order, base_price)`);
  lines.push(
    `values (${sqlStr(versionId)}, ${sqlStr(pt.id)}, ${sqlStr(pt.label)}, ${sqlStr(pt.helper)}, ${typeOrder + 1}, ${sqlNum(basePrice)});`,
  );
  lines.push("");

  flow.steps.forEach((step, stepOrder) => {
    const stepId = randomUUID();
    lines.push(`insert into public.catalogue_steps (`);
    lines.push(
      `  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional`,
    );
    lines.push(`) values (`);
    lines.push(
      `  ${sqlStr(stepId)}, ${sqlStr(versionId)}, ${sqlStr(pt.id)}, ${sqlStr(step.id)}, ${stepOrder + 1}, ${sqlStr(step.question)}, ${sqlStr(step.helper)}, ${sqlStr(step.type)}, ${sqlStr(step.role ?? "addon")}, ${sqlNum(step.min)}, ${sqlNum(step.max)}, ${sqlNum(step.pricePerUnit)}, ${sqlNum(step.includedUnits)}, ${sqlBool(!!step.optional)}`,
    );
    lines.push(`);`);

    (step.options ?? []).forEach((opt, optOrder) => {
      lines.push(`insert into public.catalogue_options (`);
      lines.push(`  step_id, option_key, label, price, multiplier, unit, description, included, option_order`);
      lines.push(`) values (`);
      lines.push(
        `  ${sqlStr(stepId)}, ${sqlStr(opt.id)}, ${sqlStr(opt.label)}, ${sqlNum(opt.price)}, ${sqlNum(opt.multiplier)}, ${sqlStr(opt.unit)}, ${sqlStr(opt.description)}, ${sqlBool(!!opt.included)}, ${optOrder + 1}`,
      );
      lines.push(`);`);
    });
    lines.push("");
  });

  writeFileSync(`${outDir}/${String(typeOrder + 1).padStart(2, "0")}_${pt.id}.sql`, lines.join("\n"));
});

let totalSteps = 0;
let totalOptions = 0;
for (const pt of PROJECT_TYPES) {
  const flow = FLOWS[pt.flow];
  totalSteps += flow.steps.length;
  for (const s of flow.steps) totalOptions += (s.options ?? []).length;
}
console.log(
  JSON.stringify({ projectTypes: PROJECT_TYPES.length, totalSteps, totalOptions, versionId, outDir }, null, 2),
);
