-- Auto-generated by scripts/gen-catalogue-seed.ts from
-- apps/studio/lib/catalogue/{catalogue,shared}.ts — do not hand-edit.

insert into public.catalogue_project_types (version_id, type_id, label, helper, type_order, base_price)
values ('400fb65c-a931-463f-a627-d1b0f04d8698', 'saas', 'SaaS Application', 'A subscription software product.', 3, 1060);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'cac2aa94-1194-4856-a20e-b9c09592f26b', '400fb65c-a931-463f-a627-d1b0f04d8698', 'saas', 'software_type', 1, 'What type of software are you building?', 'Doesn''t change the price — helps us scope it correctly.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cac2aa94-1194-4856-a20e-b9c09592f26b', 'business_management_software', 'Business management software', 0, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cac2aa94-1194-4856-a20e-b9c09592f26b', 'crm', 'CRM', 0, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cac2aa94-1194-4856-a20e-b9c09592f26b', 'erp', 'ERP', 0, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cac2aa94-1194-4856-a20e-b9c09592f26b', 'pos_system', 'POS system', 0, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cac2aa94-1194-4856-a20e-b9c09592f26b', 'inventory_management', 'Inventory management', 0, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cac2aa94-1194-4856-a20e-b9c09592f26b', 'booking_management', 'Booking management', 0, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cac2aa94-1194-4856-a20e-b9c09592f26b', 'financial_software', 'Financial software', 0, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cac2aa94-1194-4856-a20e-b9c09592f26b', 'hr_software', 'HR software', 0, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cac2aa94-1194-4856-a20e-b9c09592f26b', 'education_platform', 'Education platform', 0, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cac2aa94-1194-4856-a20e-b9c09592f26b', 'healthcare_platform', 'Healthcare platform', 0, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cac2aa94-1194-4856-a20e-b9c09592f26b', 'logistics_system', 'Logistics system', 0, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cac2aa94-1194-4856-a20e-b9c09592f26b', 'marketplace', 'Marketplace', 0, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cac2aa94-1194-4856-a20e-b9c09592f26b', 'internal_company_software', 'Internal company software', 0, null, null, null, false, 13
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cac2aa94-1194-4856-a20e-b9c09592f26b', 'data_management_system', 'Data management system', 0, null, null, null, false, 14
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cac2aa94-1194-4856-a20e-b9c09592f26b', 'other', 'Other', 0, null, null, null, false, 15
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '58fbfa0a-1d9f-4fb0-9e7b-27e6e4778a6f', '400fb65c-a931-463f-a627-d1b0f04d8698', 'saas', 'software_users', 2, 'Who will use it?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '58fbfa0a-1d9f-4fb0-9e7b-27e6e4778a6f', 'single_user', 'Single user', 0, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '58fbfa0a-1d9f-4fb0-9e7b-27e6e4778a6f', 'small_team', 'Small team', 0, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '58fbfa0a-1d9f-4fb0-9e7b-27e6e4778a6f', 'multiple_teams', 'Multiple teams', 0, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '58fbfa0a-1d9f-4fb0-9e7b-27e6e4778a6f', 'customers_staff', 'Customers + staff', 0, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '58fbfa0a-1d9f-4fb0-9e7b-27e6e4778a6f', 'public_users', 'Public users', 0, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '58fbfa0a-1d9f-4fb0-9e7b-27e6e4778a6f', 'administrators', 'Administrators', 0, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '58fbfa0a-1d9f-4fb0-9e7b-27e6e4778a6f', 'enterprise_users', 'Enterprise users', 0, null, null, null, false, 7
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '8f9f3625-1024-4ef4-9171-36870288781c', '400fb65c-a931-463f-a627-d1b0f04d8698', 'saas', 'backend', 3, 'Any backend requirements?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8f9f3625-1024-4ef4-9171-36870288781c', 'custom_database', 'Custom database architecture', 90, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8f9f3625-1024-4ef4-9171-36870288781c', 'rest_api', 'REST API', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8f9f3625-1024-4ef4-9171-36870288781c', 'graphql_api', 'GraphQL API', 120, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8f9f3625-1024-4ef4-9171-36870288781c', 'webhooks', 'Webhooks', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8f9f3625-1024-4ef4-9171-36870288781c', 'realtime', 'Real-time functionality', 90, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8f9f3625-1024-4ef4-9171-36870288781c', 'file_storage', 'File storage', 45, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8f9f3625-1024-4ef4-9171-36870288781c', 'background_jobs', 'Background jobs', 60, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8f9f3625-1024-4ef4-9171-36870288781c', 'automated_processing', 'Automated processing', 75, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8f9f3625-1024-4ef4-9171-36870288781c', 'advanced_backend_logic', 'Advanced backend logic', 120, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'aea69be7-3374-43a3-ab72-1b5913710ae8', '400fb65c-a931-463f-a627-d1b0f04d8698', 'saas', 'cms_admin', 4, 'Do you need a way to manage content or the business yourself?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aea69be7-3374-43a3-ab72-1b5913710ae8', 'basic_cms', 'Basic content management', 60, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aea69be7-3374-43a3-ab72-1b5913710ae8', 'admin_dashboard', 'Admin dashboard', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aea69be7-3374-43a3-ab72-1b5913710ae8', 'custom_admin_dashboard', 'Custom-built admin dashboard', 145, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aea69be7-3374-43a3-ab72-1b5913710ae8', 'user_management', 'User management', 60, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aea69be7-3374-43a3-ab72-1b5913710ae8', 'order_management', 'Order management', 60, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aea69be7-3374-43a3-ab72-1b5913710ae8', 'customer_management', 'Customer management', 60, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aea69be7-3374-43a3-ab72-1b5913710ae8', 'analytics_dashboard', 'Analytics dashboard', 75, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aea69be7-3374-43a3-ab72-1b5913710ae8', 'role_permissions', 'Different permissions for different users', 60, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aea69be7-3374-43a3-ab72-1b5913710ae8', 'multiple_admin_accounts', 'Multiple admin accounts', 30, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aea69be7-3374-43a3-ab72-1b5913710ae8', 'activity_logs', 'Activity logs', 45, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aea69be7-3374-43a3-ab72-1b5913710ae8', 'automated_reports', 'Automated reports', 60, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aea69be7-3374-43a3-ab72-1b5913710ae8', 'export_data', 'Export data', 25, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aea69be7-3374-43a3-ab72-1b5913710ae8', 'import_data', 'Import data', 30, null, null, null, false, 13
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '92548211-9469-4171-9941-f9feba93ef2c', '400fb65c-a931-463f-a627-d1b0f04d8698', 'saas', 'auth_security', 5, 'How should people log in, and how secure should it be?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '92548211-9469-4171-9941-f9feba93ef2c', 'email_auth', 'Email + password login', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '92548211-9469-4171-9941-f9feba93ef2c', 'google_login', 'Google login', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '92548211-9469-4171-9941-f9feba93ef2c', 'apple_login', 'Apple login', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '92548211-9469-4171-9941-f9feba93ef2c', 'social_login', 'Other social login', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '92548211-9469-4171-9941-f9feba93ef2c', 'two_factor', 'Two-factor authentication', 45, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '92548211-9469-4171-9941-f9feba93ef2c', 'otp', 'OTP verification', 30, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '92548211-9469-4171-9941-f9feba93ef2c', 'phone_verification', 'Phone verification', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '92548211-9469-4171-9941-f9feba93ef2c', 'role_based_access', 'Role-based access', 45, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '92548211-9469-4171-9941-f9feba93ef2c', 'advanced_security', 'Advanced security configuration', 60, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '92548211-9469-4171-9941-f9feba93ef2c', 'security_audit', 'Security audit', 90, null, null, null, false, 10
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '65fad193-6580-491c-8161-bc723fd92974', '400fb65c-a931-463f-a627-d1b0f04d8698', 'saas', 'payments', 6, 'How should people pay?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '65fad193-6580-491c-8161-bc723fd92974', 'payment_gateway_integration', 'Payment integration', 45, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '65fad193-6580-491c-8161-bc723fd92974', 'card_payments', 'Card payments', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '65fad193-6580-491c-8161-bc723fd92974', 'bank_transfer', 'Bank transfer', 25, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '65fad193-6580-491c-8161-bc723fd92974', 'mobile_money', 'Mobile money', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '65fad193-6580-491c-8161-bc723fd92974', 'multiple_currencies', 'Multiple currencies', 60, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '65fad193-6580-491c-8161-bc723fd92974', 'recurring_payments', 'Recurring / subscription billing', 75, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '65fad193-6580-491c-8161-bc723fd92974', 'automatic_invoices', 'Automatic invoices', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '65fad193-6580-491c-8161-bc723fd92974', 'payment_receipts', 'Payment receipts', 18, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '65fad193-6580-491c-8161-bc723fd92974', 'refund_system', 'Refund system', 30, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '65fad193-6580-491c-8161-bc723fd92974', 'split_payments', 'Split payments', 60, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '65fad193-6580-491c-8161-bc723fd92974', 'marketplace_payments', 'Marketplace payments (pay out multiple parties)', 120, null, null, null, false, 11
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '9c5b394c-c099-483b-bf3c-4edf754e010c', '400fb65c-a931-463f-a627-d1b0f04d8698', 'saas', 'integrations', 7, 'Anything this should connect to?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c5b394c-c099-483b-bf3c-4edf754e010c', 'google_services', 'Google services', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c5b394c-c099-483b-bf3c-4edf754e010c', 'google_maps', 'Google Maps', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c5b394c-c099-483b-bf3c-4edf754e010c', 'google_analytics', 'Google Analytics', 18, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c5b394c-c099-483b-bf3c-4edf754e010c', 'meta_instagram', 'Meta / Instagram', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c5b394c-c099-483b-bf3c-4edf754e010c', 'tiktok', 'TikTok', 45, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c5b394c-c099-483b-bf3c-4edf754e010c', 'whatsapp_integration', 'WhatsApp', 60, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c5b394c-c099-483b-bf3c-4edf754e010c', 'mailchimp', 'Mailchimp', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c5b394c-c099-483b-bf3c-4edf754e010c', 'hubspot', 'HubSpot', 60, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c5b394c-c099-483b-bf3c-4edf754e010c', 'salesforce', 'Salesforce', 90, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c5b394c-c099-483b-bf3c-4edf754e010c', 'slack', 'Slack', 30, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c5b394c-c099-483b-bf3c-4edf754e010c', 'custom_api_integration', 'Custom API', 90, null, null, null, false, 11
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', '400fb65c-a931-463f-a627-d1b0f04d8698', 'saas', 'design', 8, 'How should it look?', 'A standard design system is included — pick anything beyond that.', 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'custom_ui', 'Custom UI design', 60, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'premium_ui', 'Premium UI/UX', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'figma_first', 'Design mockups before development (Figma)', 60, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'custom_typography', 'Custom typography', 18, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'custom_color', 'Custom color system', 15, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'custom_icons', 'Custom iconography', 25, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'custom_illustrations', 'Custom illustrations', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'custom_graphics', 'Custom graphics', 25, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'custom_3d', 'Custom 3D elements', 60, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'interactive_ui', 'Interactive UI', 60, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'micro_interactions', 'Advanced micro-interactions', 45, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'parallax', 'Parallax effects', 25, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'scroll_animations', 'Scroll animations', 30, null, null, null, false, 13
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'page_transitions', 'Page transition animations', 30, null, null, null, false, 14
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'custom_animation', 'Custom animation', 60, null, null, null, false, 15
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'video_backgrounds', 'Video backgrounds', 30, null, null, null, false, 16
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'advanced_visual_effects', 'Advanced visual effects', 60, null, null, null, false, 17
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '027662c8-63a2-4f04-84e0-616feccc33df', 'accessibility', 'Accessibility optimization', 45, null, null, null, false, 18
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '78a54d38-80d4-4b38-b3bd-96b9d034cdf6', '400fb65c-a931-463f-a627-d1b0f04d8698', 'saas', 'revisions', 9, 'How many rounds of revisions do you want?', '2 rounds are included.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '78a54d38-80d4-4b38-b3bd-96b9d034cdf6', 'included', '2 rounds (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '78a54d38-80d4-4b38-b3bd-96b9d034cdf6', 'three', '3 rounds', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '78a54d38-80d4-4b38-b3bd-96b9d034cdf6', 'four', '4 rounds', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '78a54d38-80d4-4b38-b3bd-96b9d034cdf6', 'five', '5 rounds', 60, null, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '7df9be82-0518-4d95-b215-57b683b87457', '400fb65c-a931-463f-a627-d1b0f04d8698', 'saas', 'complexity', 10, 'How complex is this, realistically?', 'This adjusts the whole project price to reflect the extra work.', 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7df9be82-0518-4d95-b215-57b683b87457', 'standard', 'Standard — normal functionality', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7df9be82-0518-4d95-b215-57b683b87457', 'advanced', 'Advanced — more custom UI, logic, or integrations', null, 1.2, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7df9be82-0518-4d95-b215-57b683b87457', 'complex', 'Complex — substantial custom functionality, multiple integrations', null, 1.4, null, null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '04d8e0e5-9be8-44a8-b9e4-a8bf69538abc', '400fb65c-a931-463f-a627-d1b0f04d8698', 'saas', 'delivery', 11, 'How quickly do you need it?', null, 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '04d8e0e5-9be8-44a8-b9e4-a8bf69538abc', 'standard', 'Standard', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '04d8e0e5-9be8-44a8-b9e4-a8bf69538abc', 'priority', 'Priority (+15%)', null, 1.15, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '04d8e0e5-9be8-44a8-b9e4-a8bf69538abc', 'rush', 'Rush (+30%)', null, 1.3, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '04d8e0e5-9be8-44a8-b9e4-a8bf69538abc', 'emergency', 'Emergency (+50%)', null, 1.5, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'd084beff-70bb-4308-84bf-772f8aa32be0', '400fb65c-a931-463f-a627-d1b0f04d8698', 'saas', 'hosting', 12, 'Do you need hosting and infrastructure set up?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd084beff-70bb-4308-84bf-772f8aa32be0', 'hosting_setup', 'Hosting setup', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd084beff-70bb-4308-84bf-772f8aa32be0', 'domain_setup', 'Domain setup', 12, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd084beff-70bb-4308-84bf-772f8aa32be0', 'cdn_setup', 'CDN setup', 30, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd084beff-70bb-4308-84bf-772f8aa32be0', 'database_hosting', 'Database hosting setup', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd084beff-70bb-4308-84bf-772f8aa32be0', 'file_storage_setup', 'File storage setup', 25, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd084beff-70bb-4308-84bf-772f8aa32be0', 'email_service_setup', 'Email service setup', 25, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd084beff-70bb-4308-84bf-772f8aa32be0', 'monitoring', 'Monitoring', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd084beff-70bb-4308-84bf-772f8aa32be0', 'backup_system', 'Backup system', 45, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd084beff-70bb-4308-84bf-772f8aa32be0', 'production_deployment', 'Production deployment', 30, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'e52904dc-356d-4136-9f79-6d99db6ef16c', '400fb65c-a931-463f-a627-d1b0f04d8698', 'saas', 'maintenance', 13, 'Want ongoing support after launch?', '30 days of post-launch support is included either way.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e52904dc-356d-4136-9f79-6d99db6ef16c', 'none', 'Just the 30-day post-launch support (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e52904dc-356d-4136-9f79-6d99db6ef16c', 'monthly', 'Monthly maintenance — €30/month', 30, null, 'per_month', null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e52904dc-356d-4136-9f79-6d99db6ef16c', 'full', 'Full maintenance package — €90/month', 90, null, 'per_month', null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '835d6094-c366-4f8e-aa13-98100cc4c488', '400fb65c-a931-463f-a627-d1b0f04d8698', 'saas', 'custom_note', 14, 'Anything else we should know?', 'Optional. If it doesn''t fit the options above, describe it and we''ll follow up with a custom quote.', 'text', 'note', null, null, null, null, true
);
