-- Auto-generated by scripts/gen-catalogue-seed.ts from
-- apps/studio/lib/catalogue/{catalogue,shared}.ts — do not hand-edit.

insert into public.catalogue_project_types (version_id, type_id, label, helper, type_order, base_price)
values ('400fb65c-a931-463f-a627-d1b0f04d8698', 'ecommerce', 'E-commerce', 'A store that sells products or services online.', 6, null);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'c0245536-f078-4438-883e-ca7b7fe82839', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ecommerce', 'ecommerce_base', 1, 'What are you selling, and how big is the store?', null, 'single', 'base', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'c0245536-f078-4438-883e-ca7b7fe82839', 'ecommerce_website', 'E-commerce website', 440, null, null, 'Product catalog, cart, checkout, and basic payment included.', false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'c0245536-f078-4438-883e-ca7b7fe82839', 'ecommerce_platform', 'Full e-commerce platform', 700, null, null, 'Larger catalog / marketplace-scale, product catalog, cart, checkout, and basic payment included.', false, 2
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '1824e22e-ad7a-4ad7-9ff6-7a085f207910', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ecommerce', 'ecommerce', 2, 'What should your store handle?', 'Product catalog, cart, checkout, and basic payment are already included in an e-commerce base.', 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1824e22e-ad7a-4ad7-9ff6-7a085f207910', 'product_variants', 'Product variants (size, color, etc.)', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1824e22e-ad7a-4ad7-9ff6-7a085f207910', 'product_filtering', 'Product filtering', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1824e22e-ad7a-4ad7-9ff6-7a085f207910', 'multiple_payment_methods', 'Multiple payment methods', 30, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1824e22e-ad7a-4ad7-9ff6-7a085f207910', 'discount_codes', 'Discount codes', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1824e22e-ad7a-4ad7-9ff6-7a085f207910', 'tax_calculation', 'Automatic tax calculation', 30, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1824e22e-ad7a-4ad7-9ff6-7a085f207910', 'shipping_calculation', 'Shipping calculation', 45, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1824e22e-ad7a-4ad7-9ff6-7a085f207910', 'order_tracking', 'Order tracking', 45, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1824e22e-ad7a-4ad7-9ff6-7a085f207910', 'wishlist', 'Wishlist', 30, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1824e22e-ad7a-4ad7-9ff6-7a085f207910', 'product_reviews', 'Product reviews', 30, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1824e22e-ad7a-4ad7-9ff6-7a085f207910', 'inventory_management', 'Inventory management', 60, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1824e22e-ad7a-4ad7-9ff6-7a085f207910', 'stock_alerts', 'Stock alerts', 25, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1824e22e-ad7a-4ad7-9ff6-7a085f207910', 'abandoned_cart', 'Abandoned-cart recovery', 45, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1824e22e-ad7a-4ad7-9ff6-7a085f207910', 'product_recommendations', 'Product recommendations', 60, null, null, null, false, 13
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1824e22e-ad7a-4ad7-9ff6-7a085f207910', 'subscription_products', 'Subscription products', 60, null, null, null, false, 14
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1824e22e-ad7a-4ad7-9ff6-7a085f207910', 'digital_products', 'Digital products', 45, null, null, null, false, 15
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'e3021bc1-4076-4c66-8069-928626199c82', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ecommerce', 'cms_admin', 3, 'Do you need a way to manage content or the business yourself?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e3021bc1-4076-4c66-8069-928626199c82', 'basic_cms', 'Basic content management', 60, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e3021bc1-4076-4c66-8069-928626199c82', 'admin_dashboard', 'Admin dashboard', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e3021bc1-4076-4c66-8069-928626199c82', 'custom_admin_dashboard', 'Custom-built admin dashboard', 145, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e3021bc1-4076-4c66-8069-928626199c82', 'user_management', 'User management', 60, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e3021bc1-4076-4c66-8069-928626199c82', 'order_management', 'Order management', 60, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e3021bc1-4076-4c66-8069-928626199c82', 'customer_management', 'Customer management', 60, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e3021bc1-4076-4c66-8069-928626199c82', 'analytics_dashboard', 'Analytics dashboard', 75, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e3021bc1-4076-4c66-8069-928626199c82', 'role_permissions', 'Different permissions for different users', 60, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e3021bc1-4076-4c66-8069-928626199c82', 'multiple_admin_accounts', 'Multiple admin accounts', 30, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e3021bc1-4076-4c66-8069-928626199c82', 'activity_logs', 'Activity logs', 45, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e3021bc1-4076-4c66-8069-928626199c82', 'automated_reports', 'Automated reports', 60, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e3021bc1-4076-4c66-8069-928626199c82', 'export_data', 'Export data', 25, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e3021bc1-4076-4c66-8069-928626199c82', 'import_data', 'Import data', 30, null, null, null, false, 13
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'a90965db-e998-458a-a195-29e11df2904e', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ecommerce', 'design', 4, 'How should it look?', 'A standard design system is included — pick anything beyond that.', 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'custom_ui', 'Custom UI design', 60, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'premium_ui', 'Premium UI/UX', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'figma_first', 'Design mockups before development (Figma)', 60, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'custom_typography', 'Custom typography', 18, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'custom_color', 'Custom color system', 15, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'custom_icons', 'Custom iconography', 25, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'custom_illustrations', 'Custom illustrations', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'custom_graphics', 'Custom graphics', 25, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'custom_3d', 'Custom 3D elements', 60, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'interactive_ui', 'Interactive UI', 60, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'micro_interactions', 'Advanced micro-interactions', 45, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'parallax', 'Parallax effects', 25, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'scroll_animations', 'Scroll animations', 30, null, null, null, false, 13
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'page_transitions', 'Page transition animations', 30, null, null, null, false, 14
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'custom_animation', 'Custom animation', 60, null, null, null, false, 15
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'video_backgrounds', 'Video backgrounds', 30, null, null, null, false, 16
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'advanced_visual_effects', 'Advanced visual effects', 60, null, null, null, false, 17
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a90965db-e998-458a-a195-29e11df2904e', 'accessibility', 'Accessibility optimization', 45, null, null, null, false, 18
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '22d68dc8-df39-4c4d-8442-ed07d7aba0f4', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ecommerce', 'integrations', 5, 'Anything this should connect to?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '22d68dc8-df39-4c4d-8442-ed07d7aba0f4', 'google_services', 'Google services', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '22d68dc8-df39-4c4d-8442-ed07d7aba0f4', 'google_maps', 'Google Maps', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '22d68dc8-df39-4c4d-8442-ed07d7aba0f4', 'google_analytics', 'Google Analytics', 18, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '22d68dc8-df39-4c4d-8442-ed07d7aba0f4', 'meta_instagram', 'Meta / Instagram', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '22d68dc8-df39-4c4d-8442-ed07d7aba0f4', 'tiktok', 'TikTok', 45, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '22d68dc8-df39-4c4d-8442-ed07d7aba0f4', 'whatsapp_integration', 'WhatsApp', 60, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '22d68dc8-df39-4c4d-8442-ed07d7aba0f4', 'mailchimp', 'Mailchimp', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '22d68dc8-df39-4c4d-8442-ed07d7aba0f4', 'hubspot', 'HubSpot', 60, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '22d68dc8-df39-4c4d-8442-ed07d7aba0f4', 'salesforce', 'Salesforce', 90, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '22d68dc8-df39-4c4d-8442-ed07d7aba0f4', 'slack', 'Slack', 30, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '22d68dc8-df39-4c4d-8442-ed07d7aba0f4', 'custom_api_integration', 'Custom API', 90, null, null, null, false, 11
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '1a94a39d-969f-4385-b0d5-88d3e41ce220', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ecommerce', 'revisions', 6, 'How many rounds of revisions do you want?', '2 rounds are included.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1a94a39d-969f-4385-b0d5-88d3e41ce220', 'included', '2 rounds (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1a94a39d-969f-4385-b0d5-88d3e41ce220', 'three', '3 rounds', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1a94a39d-969f-4385-b0d5-88d3e41ce220', 'four', '4 rounds', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1a94a39d-969f-4385-b0d5-88d3e41ce220', 'five', '5 rounds', 60, null, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'ca522800-d34f-4c90-83f1-33d9b19a5fea', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ecommerce', 'complexity', 7, 'How complex is this, realistically?', 'This adjusts the whole project price to reflect the extra work.', 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ca522800-d34f-4c90-83f1-33d9b19a5fea', 'standard', 'Standard — normal functionality', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ca522800-d34f-4c90-83f1-33d9b19a5fea', 'advanced', 'Advanced — more custom UI, logic, or integrations', null, 1.2, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ca522800-d34f-4c90-83f1-33d9b19a5fea', 'complex', 'Complex — substantial custom functionality, multiple integrations', null, 1.4, null, null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '8a976f84-28c5-4255-9f1e-9e5f8d5f8616', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ecommerce', 'delivery', 8, 'How quickly do you need it?', null, 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8a976f84-28c5-4255-9f1e-9e5f8d5f8616', 'standard', 'Standard', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8a976f84-28c5-4255-9f1e-9e5f8d5f8616', 'priority', 'Priority (+15%)', null, 1.15, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8a976f84-28c5-4255-9f1e-9e5f8d5f8616', 'rush', 'Rush (+30%)', null, 1.3, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8a976f84-28c5-4255-9f1e-9e5f8d5f8616', 'emergency', 'Emergency (+50%)', null, 1.5, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'cc16cfd6-dfbe-4c24-9e28-c184f9d84973', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ecommerce', 'hosting', 9, 'Do you need hosting and infrastructure set up?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc16cfd6-dfbe-4c24-9e28-c184f9d84973', 'hosting_setup', 'Hosting setup', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc16cfd6-dfbe-4c24-9e28-c184f9d84973', 'domain_setup', 'Domain setup', 12, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc16cfd6-dfbe-4c24-9e28-c184f9d84973', 'cdn_setup', 'CDN setup', 30, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc16cfd6-dfbe-4c24-9e28-c184f9d84973', 'database_hosting', 'Database hosting setup', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc16cfd6-dfbe-4c24-9e28-c184f9d84973', 'file_storage_setup', 'File storage setup', 25, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc16cfd6-dfbe-4c24-9e28-c184f9d84973', 'email_service_setup', 'Email service setup', 25, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc16cfd6-dfbe-4c24-9e28-c184f9d84973', 'monitoring', 'Monitoring', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc16cfd6-dfbe-4c24-9e28-c184f9d84973', 'backup_system', 'Backup system', 45, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc16cfd6-dfbe-4c24-9e28-c184f9d84973', 'production_deployment', 'Production deployment', 30, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '40d7c801-5559-4259-b07e-9ecf4bcdc9a9', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ecommerce', 'maintenance', 10, 'Want ongoing support after launch?', '30 days of post-launch support is included either way.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '40d7c801-5559-4259-b07e-9ecf4bcdc9a9', 'none', 'Just the 30-day post-launch support (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '40d7c801-5559-4259-b07e-9ecf4bcdc9a9', 'monthly', 'Monthly maintenance — €30/month', 30, null, 'per_month', null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '40d7c801-5559-4259-b07e-9ecf4bcdc9a9', 'full', 'Full maintenance package — €90/month', 90, null, 'per_month', null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'daeb3574-2326-4063-a37a-927c06bb3e11', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ecommerce', 'custom_note', 11, 'Anything else we should know?', 'Optional. If it doesn''t fit the options above, describe it and we''ll follow up with a custom quote.', 'text', 'note', null, null, null, null, true
);
