-- Auto-generated by scripts/gen-catalogue-seed.ts from
-- apps/studio/lib/catalogue/{catalogue,shared}.ts — do not hand-edit.

insert into public.catalogue_project_types (version_id, type_id, label, helper, type_order, base_price)
values ('400fb65c-a931-463f-a627-d1b0f04d8698', 'custom_software', 'Custom Software', 'Internal or business-specific software.', 4, 1175);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '82876011-9766-4467-8829-bfe99c34e400', '400fb65c-a931-463f-a627-d1b0f04d8698', 'custom_software', 'software_type', 1, 'What type of software are you building?', 'Doesn''t change the price — helps us scope it correctly.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '82876011-9766-4467-8829-bfe99c34e400', 'business_management_software', 'Business management software', 0, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '82876011-9766-4467-8829-bfe99c34e400', 'crm', 'CRM', 0, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '82876011-9766-4467-8829-bfe99c34e400', 'erp', 'ERP', 0, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '82876011-9766-4467-8829-bfe99c34e400', 'pos_system', 'POS system', 0, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '82876011-9766-4467-8829-bfe99c34e400', 'inventory_management', 'Inventory management', 0, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '82876011-9766-4467-8829-bfe99c34e400', 'booking_management', 'Booking management', 0, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '82876011-9766-4467-8829-bfe99c34e400', 'financial_software', 'Financial software', 0, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '82876011-9766-4467-8829-bfe99c34e400', 'hr_software', 'HR software', 0, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '82876011-9766-4467-8829-bfe99c34e400', 'education_platform', 'Education platform', 0, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '82876011-9766-4467-8829-bfe99c34e400', 'healthcare_platform', 'Healthcare platform', 0, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '82876011-9766-4467-8829-bfe99c34e400', 'logistics_system', 'Logistics system', 0, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '82876011-9766-4467-8829-bfe99c34e400', 'marketplace', 'Marketplace', 0, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '82876011-9766-4467-8829-bfe99c34e400', 'internal_company_software', 'Internal company software', 0, null, null, null, false, 13
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '82876011-9766-4467-8829-bfe99c34e400', 'data_management_system', 'Data management system', 0, null, null, null, false, 14
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '82876011-9766-4467-8829-bfe99c34e400', 'other', 'Other', 0, null, null, null, false, 15
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'b93f74f1-7aeb-4117-8d7a-d9262f5a2178', '400fb65c-a931-463f-a627-d1b0f04d8698', 'custom_software', 'software_users', 2, 'Who will use it?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b93f74f1-7aeb-4117-8d7a-d9262f5a2178', 'single_user', 'Single user', 0, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b93f74f1-7aeb-4117-8d7a-d9262f5a2178', 'small_team', 'Small team', 0, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b93f74f1-7aeb-4117-8d7a-d9262f5a2178', 'multiple_teams', 'Multiple teams', 0, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b93f74f1-7aeb-4117-8d7a-d9262f5a2178', 'customers_staff', 'Customers + staff', 0, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b93f74f1-7aeb-4117-8d7a-d9262f5a2178', 'public_users', 'Public users', 0, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b93f74f1-7aeb-4117-8d7a-d9262f5a2178', 'administrators', 'Administrators', 0, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b93f74f1-7aeb-4117-8d7a-d9262f5a2178', 'enterprise_users', 'Enterprise users', 0, null, null, null, false, 7
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'b3332894-7056-407b-a8fb-e2f9257252a0', '400fb65c-a931-463f-a627-d1b0f04d8698', 'custom_software', 'backend', 3, 'Any backend requirements?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b3332894-7056-407b-a8fb-e2f9257252a0', 'custom_database', 'Custom database architecture', 90, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b3332894-7056-407b-a8fb-e2f9257252a0', 'rest_api', 'REST API', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b3332894-7056-407b-a8fb-e2f9257252a0', 'graphql_api', 'GraphQL API', 120, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b3332894-7056-407b-a8fb-e2f9257252a0', 'webhooks', 'Webhooks', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b3332894-7056-407b-a8fb-e2f9257252a0', 'realtime', 'Real-time functionality', 90, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b3332894-7056-407b-a8fb-e2f9257252a0', 'file_storage', 'File storage', 45, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b3332894-7056-407b-a8fb-e2f9257252a0', 'background_jobs', 'Background jobs', 60, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b3332894-7056-407b-a8fb-e2f9257252a0', 'automated_processing', 'Automated processing', 75, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b3332894-7056-407b-a8fb-e2f9257252a0', 'advanced_backend_logic', 'Advanced backend logic', 120, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'ac8f6836-46d6-44fd-83cf-33aa3be9910d', '400fb65c-a931-463f-a627-d1b0f04d8698', 'custom_software', 'cms_admin', 4, 'Do you need a way to manage content or the business yourself?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ac8f6836-46d6-44fd-83cf-33aa3be9910d', 'basic_cms', 'Basic content management', 60, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ac8f6836-46d6-44fd-83cf-33aa3be9910d', 'admin_dashboard', 'Admin dashboard', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ac8f6836-46d6-44fd-83cf-33aa3be9910d', 'custom_admin_dashboard', 'Custom-built admin dashboard', 145, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ac8f6836-46d6-44fd-83cf-33aa3be9910d', 'user_management', 'User management', 60, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ac8f6836-46d6-44fd-83cf-33aa3be9910d', 'order_management', 'Order management', 60, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ac8f6836-46d6-44fd-83cf-33aa3be9910d', 'customer_management', 'Customer management', 60, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ac8f6836-46d6-44fd-83cf-33aa3be9910d', 'analytics_dashboard', 'Analytics dashboard', 75, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ac8f6836-46d6-44fd-83cf-33aa3be9910d', 'role_permissions', 'Different permissions for different users', 60, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ac8f6836-46d6-44fd-83cf-33aa3be9910d', 'multiple_admin_accounts', 'Multiple admin accounts', 30, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ac8f6836-46d6-44fd-83cf-33aa3be9910d', 'activity_logs', 'Activity logs', 45, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ac8f6836-46d6-44fd-83cf-33aa3be9910d', 'automated_reports', 'Automated reports', 60, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ac8f6836-46d6-44fd-83cf-33aa3be9910d', 'export_data', 'Export data', 25, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ac8f6836-46d6-44fd-83cf-33aa3be9910d', 'import_data', 'Import data', 30, null, null, null, false, 13
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'e79d3708-375b-4747-8112-019ca5197a01', '400fb65c-a931-463f-a627-d1b0f04d8698', 'custom_software', 'auth_security', 5, 'How should people log in, and how secure should it be?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e79d3708-375b-4747-8112-019ca5197a01', 'email_auth', 'Email + password login', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e79d3708-375b-4747-8112-019ca5197a01', 'google_login', 'Google login', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e79d3708-375b-4747-8112-019ca5197a01', 'apple_login', 'Apple login', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e79d3708-375b-4747-8112-019ca5197a01', 'social_login', 'Other social login', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e79d3708-375b-4747-8112-019ca5197a01', 'two_factor', 'Two-factor authentication', 45, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e79d3708-375b-4747-8112-019ca5197a01', 'otp', 'OTP verification', 30, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e79d3708-375b-4747-8112-019ca5197a01', 'phone_verification', 'Phone verification', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e79d3708-375b-4747-8112-019ca5197a01', 'role_based_access', 'Role-based access', 45, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e79d3708-375b-4747-8112-019ca5197a01', 'advanced_security', 'Advanced security configuration', 60, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e79d3708-375b-4747-8112-019ca5197a01', 'security_audit', 'Security audit', 90, null, null, null, false, 10
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '6a0693c6-fac7-48d4-9038-02616b4701bf', '400fb65c-a931-463f-a627-d1b0f04d8698', 'custom_software', 'payments', 6, 'How should people pay?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6a0693c6-fac7-48d4-9038-02616b4701bf', 'payment_gateway_integration', 'Payment integration', 45, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6a0693c6-fac7-48d4-9038-02616b4701bf', 'card_payments', 'Card payments', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6a0693c6-fac7-48d4-9038-02616b4701bf', 'bank_transfer', 'Bank transfer', 25, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6a0693c6-fac7-48d4-9038-02616b4701bf', 'mobile_money', 'Mobile money', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6a0693c6-fac7-48d4-9038-02616b4701bf', 'multiple_currencies', 'Multiple currencies', 60, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6a0693c6-fac7-48d4-9038-02616b4701bf', 'recurring_payments', 'Recurring / subscription billing', 75, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6a0693c6-fac7-48d4-9038-02616b4701bf', 'automatic_invoices', 'Automatic invoices', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6a0693c6-fac7-48d4-9038-02616b4701bf', 'payment_receipts', 'Payment receipts', 18, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6a0693c6-fac7-48d4-9038-02616b4701bf', 'refund_system', 'Refund system', 30, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6a0693c6-fac7-48d4-9038-02616b4701bf', 'split_payments', 'Split payments', 60, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6a0693c6-fac7-48d4-9038-02616b4701bf', 'marketplace_payments', 'Marketplace payments (pay out multiple parties)', 120, null, null, null, false, 11
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'db2ae73a-5757-404e-9d8e-dce534b7d380', '400fb65c-a931-463f-a627-d1b0f04d8698', 'custom_software', 'integrations', 7, 'Anything this should connect to?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'db2ae73a-5757-404e-9d8e-dce534b7d380', 'google_services', 'Google services', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'db2ae73a-5757-404e-9d8e-dce534b7d380', 'google_maps', 'Google Maps', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'db2ae73a-5757-404e-9d8e-dce534b7d380', 'google_analytics', 'Google Analytics', 18, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'db2ae73a-5757-404e-9d8e-dce534b7d380', 'meta_instagram', 'Meta / Instagram', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'db2ae73a-5757-404e-9d8e-dce534b7d380', 'tiktok', 'TikTok', 45, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'db2ae73a-5757-404e-9d8e-dce534b7d380', 'whatsapp_integration', 'WhatsApp', 60, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'db2ae73a-5757-404e-9d8e-dce534b7d380', 'mailchimp', 'Mailchimp', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'db2ae73a-5757-404e-9d8e-dce534b7d380', 'hubspot', 'HubSpot', 60, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'db2ae73a-5757-404e-9d8e-dce534b7d380', 'salesforce', 'Salesforce', 90, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'db2ae73a-5757-404e-9d8e-dce534b7d380', 'slack', 'Slack', 30, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'db2ae73a-5757-404e-9d8e-dce534b7d380', 'custom_api_integration', 'Custom API', 90, null, null, null, false, 11
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', '400fb65c-a931-463f-a627-d1b0f04d8698', 'custom_software', 'design', 8, 'How should it look?', 'A standard design system is included — pick anything beyond that.', 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'custom_ui', 'Custom UI design', 60, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'premium_ui', 'Premium UI/UX', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'figma_first', 'Design mockups before development (Figma)', 60, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'custom_typography', 'Custom typography', 18, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'custom_color', 'Custom color system', 15, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'custom_icons', 'Custom iconography', 25, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'custom_illustrations', 'Custom illustrations', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'custom_graphics', 'Custom graphics', 25, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'custom_3d', 'Custom 3D elements', 60, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'interactive_ui', 'Interactive UI', 60, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'micro_interactions', 'Advanced micro-interactions', 45, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'parallax', 'Parallax effects', 25, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'scroll_animations', 'Scroll animations', 30, null, null, null, false, 13
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'page_transitions', 'Page transition animations', 30, null, null, null, false, 14
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'custom_animation', 'Custom animation', 60, null, null, null, false, 15
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'video_backgrounds', 'Video backgrounds', 30, null, null, null, false, 16
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'advanced_visual_effects', 'Advanced visual effects', 60, null, null, null, false, 17
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cce544fc-1b1c-4575-8c35-2dd3ff1be115', 'accessibility', 'Accessibility optimization', 45, null, null, null, false, 18
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '1c7c2335-e5c0-410b-8723-f8298b61d66d', '400fb65c-a931-463f-a627-d1b0f04d8698', 'custom_software', 'revisions', 9, 'How many rounds of revisions do you want?', '2 rounds are included.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1c7c2335-e5c0-410b-8723-f8298b61d66d', 'included', '2 rounds (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1c7c2335-e5c0-410b-8723-f8298b61d66d', 'three', '3 rounds', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1c7c2335-e5c0-410b-8723-f8298b61d66d', 'four', '4 rounds', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1c7c2335-e5c0-410b-8723-f8298b61d66d', 'five', '5 rounds', 60, null, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'f40bf1fd-c900-4cf8-aa8b-ec219a81672f', '400fb65c-a931-463f-a627-d1b0f04d8698', 'custom_software', 'complexity', 10, 'How complex is this, realistically?', 'This adjusts the whole project price to reflect the extra work.', 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'f40bf1fd-c900-4cf8-aa8b-ec219a81672f', 'standard', 'Standard — normal functionality', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'f40bf1fd-c900-4cf8-aa8b-ec219a81672f', 'advanced', 'Advanced — more custom UI, logic, or integrations', null, 1.2, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'f40bf1fd-c900-4cf8-aa8b-ec219a81672f', 'complex', 'Complex — substantial custom functionality, multiple integrations', null, 1.4, null, null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'f3337727-6b32-4145-b0c8-9d2540ca52cd', '400fb65c-a931-463f-a627-d1b0f04d8698', 'custom_software', 'delivery', 11, 'How quickly do you need it?', null, 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'f3337727-6b32-4145-b0c8-9d2540ca52cd', 'standard', 'Standard', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'f3337727-6b32-4145-b0c8-9d2540ca52cd', 'priority', 'Priority (+15%)', null, 1.15, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'f3337727-6b32-4145-b0c8-9d2540ca52cd', 'rush', 'Rush (+30%)', null, 1.3, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'f3337727-6b32-4145-b0c8-9d2540ca52cd', 'emergency', 'Emergency (+50%)', null, 1.5, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '472e6620-f021-46f5-acbd-045e8c943867', '400fb65c-a931-463f-a627-d1b0f04d8698', 'custom_software', 'hosting', 12, 'Do you need hosting and infrastructure set up?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '472e6620-f021-46f5-acbd-045e8c943867', 'hosting_setup', 'Hosting setup', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '472e6620-f021-46f5-acbd-045e8c943867', 'domain_setup', 'Domain setup', 12, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '472e6620-f021-46f5-acbd-045e8c943867', 'cdn_setup', 'CDN setup', 30, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '472e6620-f021-46f5-acbd-045e8c943867', 'database_hosting', 'Database hosting setup', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '472e6620-f021-46f5-acbd-045e8c943867', 'file_storage_setup', 'File storage setup', 25, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '472e6620-f021-46f5-acbd-045e8c943867', 'email_service_setup', 'Email service setup', 25, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '472e6620-f021-46f5-acbd-045e8c943867', 'monitoring', 'Monitoring', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '472e6620-f021-46f5-acbd-045e8c943867', 'backup_system', 'Backup system', 45, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '472e6620-f021-46f5-acbd-045e8c943867', 'production_deployment', 'Production deployment', 30, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '8882df46-6575-45ee-a2b8-78f61c3b06c8', '400fb65c-a931-463f-a627-d1b0f04d8698', 'custom_software', 'maintenance', 13, 'Want ongoing support after launch?', '30 days of post-launch support is included either way.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8882df46-6575-45ee-a2b8-78f61c3b06c8', 'none', 'Just the 30-day post-launch support (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8882df46-6575-45ee-a2b8-78f61c3b06c8', 'monthly', 'Monthly maintenance — €30/month', 30, null, 'per_month', null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8882df46-6575-45ee-a2b8-78f61c3b06c8', 'full', 'Full maintenance package — €90/month', 90, null, 'per_month', null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '45e36dec-cbac-4b1e-81e0-90068edf76de', '400fb65c-a931-463f-a627-d1b0f04d8698', 'custom_software', 'custom_note', 14, 'Anything else we should know?', 'Optional. If it doesn''t fit the options above, describe it and we''ll follow up with a custom quote.', 'text', 'note', null, null, null, null, true
);
