-- Auto-generated by scripts/gen-catalogue-seed.ts from
-- apps/studio/lib/catalogue/{catalogue,shared}.ts — do not hand-edit.

insert into public.catalogue_project_types (version_id, type_id, label, helper, type_order, base_price)
values ('400fb65c-a931-463f-a627-d1b0f04d8698', 'marketing', 'Marketing', 'SEO, content, and growth.', 12, 145);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'af8774a3-8ae0-4dfd-accf-992827cf1688', '400fb65c-a931-463f-a627-d1b0f04d8698', 'marketing', 'marketing_items', 1, 'What do you need?', null, 'multi', 'addon', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'af8774a3-8ae0-4dfd-accf-992827cf1688', 'technical_seo', 'Technical SEO', 60, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'af8774a3-8ae0-4dfd-accf-992827cf1688', 'keyword_research', 'Keyword research', 45, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'af8774a3-8ae0-4dfd-accf-992827cf1688', 'on_page_seo', 'On-page SEO', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'af8774a3-8ae0-4dfd-accf-992827cf1688', 'schema_markup', 'Schema markup', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'af8774a3-8ae0-4dfd-accf-992827cf1688', 'gsc_setup', 'Google Search Console setup', 18, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'af8774a3-8ae0-4dfd-accf-992827cf1688', 'analytics_setup', 'Analytics setup', 18, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'af8774a3-8ae0-4dfd-accf-992827cf1688', 'seo_content', 'SEO content (per article)', 20, null, 'per_article', null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'af8774a3-8ae0-4dfd-accf-992827cf1688', 'blog_setup', 'Blog setup', 30, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'af8774a3-8ae0-4dfd-accf-992827cf1688', 'social_integration', 'Social media integration', 25, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'af8774a3-8ae0-4dfd-accf-992827cf1688', 'email_marketing_setup', 'Email marketing setup', 45, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'af8774a3-8ae0-4dfd-accf-992827cf1688', 'newsletter_system', 'Newsletter system', 45, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'af8774a3-8ae0-4dfd-accf-992827cf1688', 'lead_gen_system', 'Lead-generation system', 60, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'af8774a3-8ae0-4dfd-accf-992827cf1688', 'conversion_optimization', 'Conversion optimization', 60, null, null, null, false, 13
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'af8774a3-8ae0-4dfd-accf-992827cf1688', 'marketing_automation', 'Marketing automation', 90, null, null, null, false, 14
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'b2d6f47f-a43c-489b-a03c-999beb4a0e77', '400fb65c-a931-463f-a627-d1b0f04d8698', 'marketing', 'revisions', 2, 'How many rounds of revisions do you want?', '2 rounds are included.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b2d6f47f-a43c-489b-a03c-999beb4a0e77', 'included', '2 rounds (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b2d6f47f-a43c-489b-a03c-999beb4a0e77', 'three', '3 rounds', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b2d6f47f-a43c-489b-a03c-999beb4a0e77', 'four', '4 rounds', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b2d6f47f-a43c-489b-a03c-999beb4a0e77', 'five', '5 rounds', 60, null, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'db3c0a20-2248-472c-a38e-ccc744e778c8', '400fb65c-a931-463f-a627-d1b0f04d8698', 'marketing', 'delivery', 3, 'How quickly do you need it?', null, 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'db3c0a20-2248-472c-a38e-ccc744e778c8', 'standard', 'Standard', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'db3c0a20-2248-472c-a38e-ccc744e778c8', 'priority', 'Priority (+15%)', null, 1.15, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'db3c0a20-2248-472c-a38e-ccc744e778c8', 'rush', 'Rush (+30%)', null, 1.3, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'db3c0a20-2248-472c-a38e-ccc744e778c8', 'emergency', 'Emergency (+50%)', null, 1.5, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'c691ff2d-423e-42a3-bc83-2ca22f3b2ba9', '400fb65c-a931-463f-a627-d1b0f04d8698', 'marketing', 'custom_note', 4, 'Anything else we should know?', 'Optional. If it doesn''t fit the options above, describe it and we''ll follow up with a custom quote.', 'text', 'note', null, null, null, null, true
);
