-- Auto-generated by scripts/gen-catalogue-seed.ts from
-- apps/studio/lib/catalogue/{catalogue,shared}.ts — do not hand-edit.

insert into public.catalogue_project_types (version_id, type_id, label, helper, type_order, base_price)
values ('400fb65c-a931-463f-a627-d1b0f04d8698', 'web_app', 'Web App', 'An interactive product people log into and use.', 2, 705);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'b0ab8650-d588-466c-a22e-7a3e12b936c9', '400fb65c-a931-463f-a627-d1b0f04d8698', 'web_app', 'software_type', 1, 'What type of software are you building?', 'Doesn''t change the price — helps us scope it correctly.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ab8650-d588-466c-a22e-7a3e12b936c9', 'business_management_software', 'Business management software', 0, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ab8650-d588-466c-a22e-7a3e12b936c9', 'crm', 'CRM', 0, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ab8650-d588-466c-a22e-7a3e12b936c9', 'erp', 'ERP', 0, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ab8650-d588-466c-a22e-7a3e12b936c9', 'pos_system', 'POS system', 0, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ab8650-d588-466c-a22e-7a3e12b936c9', 'inventory_management', 'Inventory management', 0, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ab8650-d588-466c-a22e-7a3e12b936c9', 'booking_management', 'Booking management', 0, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ab8650-d588-466c-a22e-7a3e12b936c9', 'financial_software', 'Financial software', 0, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ab8650-d588-466c-a22e-7a3e12b936c9', 'hr_software', 'HR software', 0, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ab8650-d588-466c-a22e-7a3e12b936c9', 'education_platform', 'Education platform', 0, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ab8650-d588-466c-a22e-7a3e12b936c9', 'healthcare_platform', 'Healthcare platform', 0, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ab8650-d588-466c-a22e-7a3e12b936c9', 'logistics_system', 'Logistics system', 0, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ab8650-d588-466c-a22e-7a3e12b936c9', 'marketplace', 'Marketplace', 0, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ab8650-d588-466c-a22e-7a3e12b936c9', 'internal_company_software', 'Internal company software', 0, null, null, null, false, 13
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ab8650-d588-466c-a22e-7a3e12b936c9', 'data_management_system', 'Data management system', 0, null, null, null, false, 14
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ab8650-d588-466c-a22e-7a3e12b936c9', 'other', 'Other', 0, null, null, null, false, 15
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '8cefcdf8-7ca6-4422-9919-20b089b44614', '400fb65c-a931-463f-a627-d1b0f04d8698', 'web_app', 'software_users', 2, 'Who will use it?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8cefcdf8-7ca6-4422-9919-20b089b44614', 'single_user', 'Single user', 0, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8cefcdf8-7ca6-4422-9919-20b089b44614', 'small_team', 'Small team', 0, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8cefcdf8-7ca6-4422-9919-20b089b44614', 'multiple_teams', 'Multiple teams', 0, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8cefcdf8-7ca6-4422-9919-20b089b44614', 'customers_staff', 'Customers + staff', 0, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8cefcdf8-7ca6-4422-9919-20b089b44614', 'public_users', 'Public users', 0, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8cefcdf8-7ca6-4422-9919-20b089b44614', 'administrators', 'Administrators', 0, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8cefcdf8-7ca6-4422-9919-20b089b44614', 'enterprise_users', 'Enterprise users', 0, null, null, null, false, 7
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '5a13043f-c99b-4a0b-8de8-88b62d7ec38f', '400fb65c-a931-463f-a627-d1b0f04d8698', 'web_app', 'backend', 3, 'Any backend requirements?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5a13043f-c99b-4a0b-8de8-88b62d7ec38f', 'custom_database', 'Custom database architecture', 90, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5a13043f-c99b-4a0b-8de8-88b62d7ec38f', 'rest_api', 'REST API', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5a13043f-c99b-4a0b-8de8-88b62d7ec38f', 'graphql_api', 'GraphQL API', 120, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5a13043f-c99b-4a0b-8de8-88b62d7ec38f', 'webhooks', 'Webhooks', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5a13043f-c99b-4a0b-8de8-88b62d7ec38f', 'realtime', 'Real-time functionality', 90, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5a13043f-c99b-4a0b-8de8-88b62d7ec38f', 'file_storage', 'File storage', 45, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5a13043f-c99b-4a0b-8de8-88b62d7ec38f', 'background_jobs', 'Background jobs', 60, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5a13043f-c99b-4a0b-8de8-88b62d7ec38f', 'automated_processing', 'Automated processing', 75, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5a13043f-c99b-4a0b-8de8-88b62d7ec38f', 'advanced_backend_logic', 'Advanced backend logic', 120, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '81c68ed7-12c2-46c3-b91a-9ddd00191a0d', '400fb65c-a931-463f-a627-d1b0f04d8698', 'web_app', 'cms_admin', 4, 'Do you need a way to manage content or the business yourself?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '81c68ed7-12c2-46c3-b91a-9ddd00191a0d', 'basic_cms', 'Basic content management', 60, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '81c68ed7-12c2-46c3-b91a-9ddd00191a0d', 'admin_dashboard', 'Admin dashboard', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '81c68ed7-12c2-46c3-b91a-9ddd00191a0d', 'custom_admin_dashboard', 'Custom-built admin dashboard', 145, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '81c68ed7-12c2-46c3-b91a-9ddd00191a0d', 'user_management', 'User management', 60, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '81c68ed7-12c2-46c3-b91a-9ddd00191a0d', 'order_management', 'Order management', 60, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '81c68ed7-12c2-46c3-b91a-9ddd00191a0d', 'customer_management', 'Customer management', 60, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '81c68ed7-12c2-46c3-b91a-9ddd00191a0d', 'analytics_dashboard', 'Analytics dashboard', 75, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '81c68ed7-12c2-46c3-b91a-9ddd00191a0d', 'role_permissions', 'Different permissions for different users', 60, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '81c68ed7-12c2-46c3-b91a-9ddd00191a0d', 'multiple_admin_accounts', 'Multiple admin accounts', 30, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '81c68ed7-12c2-46c3-b91a-9ddd00191a0d', 'activity_logs', 'Activity logs', 45, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '81c68ed7-12c2-46c3-b91a-9ddd00191a0d', 'automated_reports', 'Automated reports', 60, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '81c68ed7-12c2-46c3-b91a-9ddd00191a0d', 'export_data', 'Export data', 25, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '81c68ed7-12c2-46c3-b91a-9ddd00191a0d', 'import_data', 'Import data', 30, null, null, null, false, 13
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '7e9f70c6-1a7f-484e-8a4d-5a724e1766df', '400fb65c-a931-463f-a627-d1b0f04d8698', 'web_app', 'auth_security', 5, 'How should people log in, and how secure should it be?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7e9f70c6-1a7f-484e-8a4d-5a724e1766df', 'email_auth', 'Email + password login', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7e9f70c6-1a7f-484e-8a4d-5a724e1766df', 'google_login', 'Google login', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7e9f70c6-1a7f-484e-8a4d-5a724e1766df', 'apple_login', 'Apple login', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7e9f70c6-1a7f-484e-8a4d-5a724e1766df', 'social_login', 'Other social login', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7e9f70c6-1a7f-484e-8a4d-5a724e1766df', 'two_factor', 'Two-factor authentication', 45, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7e9f70c6-1a7f-484e-8a4d-5a724e1766df', 'otp', 'OTP verification', 30, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7e9f70c6-1a7f-484e-8a4d-5a724e1766df', 'phone_verification', 'Phone verification', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7e9f70c6-1a7f-484e-8a4d-5a724e1766df', 'role_based_access', 'Role-based access', 45, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7e9f70c6-1a7f-484e-8a4d-5a724e1766df', 'advanced_security', 'Advanced security configuration', 60, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7e9f70c6-1a7f-484e-8a4d-5a724e1766df', 'security_audit', 'Security audit', 90, null, null, null, false, 10
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'b9e98606-8efb-4ac9-a243-791520b5d149', '400fb65c-a931-463f-a627-d1b0f04d8698', 'web_app', 'payments', 6, 'How should people pay?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b9e98606-8efb-4ac9-a243-791520b5d149', 'payment_gateway_integration', 'Payment integration', 45, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b9e98606-8efb-4ac9-a243-791520b5d149', 'card_payments', 'Card payments', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b9e98606-8efb-4ac9-a243-791520b5d149', 'bank_transfer', 'Bank transfer', 25, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b9e98606-8efb-4ac9-a243-791520b5d149', 'mobile_money', 'Mobile money', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b9e98606-8efb-4ac9-a243-791520b5d149', 'multiple_currencies', 'Multiple currencies', 60, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b9e98606-8efb-4ac9-a243-791520b5d149', 'recurring_payments', 'Recurring / subscription billing', 75, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b9e98606-8efb-4ac9-a243-791520b5d149', 'automatic_invoices', 'Automatic invoices', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b9e98606-8efb-4ac9-a243-791520b5d149', 'payment_receipts', 'Payment receipts', 18, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b9e98606-8efb-4ac9-a243-791520b5d149', 'refund_system', 'Refund system', 30, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b9e98606-8efb-4ac9-a243-791520b5d149', 'split_payments', 'Split payments', 60, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b9e98606-8efb-4ac9-a243-791520b5d149', 'marketplace_payments', 'Marketplace payments (pay out multiple parties)', 120, null, null, null, false, 11
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'cc0d4442-f4f8-456a-beba-ae5c725e29c7', '400fb65c-a931-463f-a627-d1b0f04d8698', 'web_app', 'integrations', 7, 'Anything this should connect to?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc0d4442-f4f8-456a-beba-ae5c725e29c7', 'google_services', 'Google services', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc0d4442-f4f8-456a-beba-ae5c725e29c7', 'google_maps', 'Google Maps', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc0d4442-f4f8-456a-beba-ae5c725e29c7', 'google_analytics', 'Google Analytics', 18, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc0d4442-f4f8-456a-beba-ae5c725e29c7', 'meta_instagram', 'Meta / Instagram', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc0d4442-f4f8-456a-beba-ae5c725e29c7', 'tiktok', 'TikTok', 45, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc0d4442-f4f8-456a-beba-ae5c725e29c7', 'whatsapp_integration', 'WhatsApp', 60, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc0d4442-f4f8-456a-beba-ae5c725e29c7', 'mailchimp', 'Mailchimp', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc0d4442-f4f8-456a-beba-ae5c725e29c7', 'hubspot', 'HubSpot', 60, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc0d4442-f4f8-456a-beba-ae5c725e29c7', 'salesforce', 'Salesforce', 90, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc0d4442-f4f8-456a-beba-ae5c725e29c7', 'slack', 'Slack', 30, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cc0d4442-f4f8-456a-beba-ae5c725e29c7', 'custom_api_integration', 'Custom API', 90, null, null, null, false, 11
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', '400fb65c-a931-463f-a627-d1b0f04d8698', 'web_app', 'design', 8, 'How should it look?', 'A standard design system is included — pick anything beyond that.', 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'custom_ui', 'Custom UI design', 60, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'premium_ui', 'Premium UI/UX', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'figma_first', 'Design mockups before development (Figma)', 60, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'custom_typography', 'Custom typography', 18, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'custom_color', 'Custom color system', 15, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'custom_icons', 'Custom iconography', 25, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'custom_illustrations', 'Custom illustrations', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'custom_graphics', 'Custom graphics', 25, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'custom_3d', 'Custom 3D elements', 60, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'interactive_ui', 'Interactive UI', 60, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'micro_interactions', 'Advanced micro-interactions', 45, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'parallax', 'Parallax effects', 25, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'scroll_animations', 'Scroll animations', 30, null, null, null, false, 13
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'page_transitions', 'Page transition animations', 30, null, null, null, false, 14
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'custom_animation', 'Custom animation', 60, null, null, null, false, 15
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'video_backgrounds', 'Video backgrounds', 30, null, null, null, false, 16
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'advanced_visual_effects', 'Advanced visual effects', 60, null, null, null, false, 17
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1f9c91c3-d56c-46ac-bd68-9d56fab24fe3', 'accessibility', 'Accessibility optimization', 45, null, null, null, false, 18
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'b7466542-313d-47f8-8818-78ed3e026a2b', '400fb65c-a931-463f-a627-d1b0f04d8698', 'web_app', 'revisions', 9, 'How many rounds of revisions do you want?', '2 rounds are included.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b7466542-313d-47f8-8818-78ed3e026a2b', 'included', '2 rounds (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b7466542-313d-47f8-8818-78ed3e026a2b', 'three', '3 rounds', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b7466542-313d-47f8-8818-78ed3e026a2b', 'four', '4 rounds', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b7466542-313d-47f8-8818-78ed3e026a2b', 'five', '5 rounds', 60, null, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '4e6cc828-1e1d-41e8-8733-c4c7865f293f', '400fb65c-a931-463f-a627-d1b0f04d8698', 'web_app', 'complexity', 10, 'How complex is this, realistically?', 'This adjusts the whole project price to reflect the extra work.', 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4e6cc828-1e1d-41e8-8733-c4c7865f293f', 'standard', 'Standard — normal functionality', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4e6cc828-1e1d-41e8-8733-c4c7865f293f', 'advanced', 'Advanced — more custom UI, logic, or integrations', null, 1.2, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4e6cc828-1e1d-41e8-8733-c4c7865f293f', 'complex', 'Complex — substantial custom functionality, multiple integrations', null, 1.4, null, null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '6b2afdf7-f605-43e8-93cf-b40a9b6b1668', '400fb65c-a931-463f-a627-d1b0f04d8698', 'web_app', 'delivery', 11, 'How quickly do you need it?', null, 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6b2afdf7-f605-43e8-93cf-b40a9b6b1668', 'standard', 'Standard', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6b2afdf7-f605-43e8-93cf-b40a9b6b1668', 'priority', 'Priority (+15%)', null, 1.15, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6b2afdf7-f605-43e8-93cf-b40a9b6b1668', 'rush', 'Rush (+30%)', null, 1.3, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6b2afdf7-f605-43e8-93cf-b40a9b6b1668', 'emergency', 'Emergency (+50%)', null, 1.5, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'a9c8b3bb-6ad0-4fd2-8bec-d488f13831e5', '400fb65c-a931-463f-a627-d1b0f04d8698', 'web_app', 'hosting', 12, 'Do you need hosting and infrastructure set up?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a9c8b3bb-6ad0-4fd2-8bec-d488f13831e5', 'hosting_setup', 'Hosting setup', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a9c8b3bb-6ad0-4fd2-8bec-d488f13831e5', 'domain_setup', 'Domain setup', 12, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a9c8b3bb-6ad0-4fd2-8bec-d488f13831e5', 'cdn_setup', 'CDN setup', 30, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a9c8b3bb-6ad0-4fd2-8bec-d488f13831e5', 'database_hosting', 'Database hosting setup', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a9c8b3bb-6ad0-4fd2-8bec-d488f13831e5', 'file_storage_setup', 'File storage setup', 25, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a9c8b3bb-6ad0-4fd2-8bec-d488f13831e5', 'email_service_setup', 'Email service setup', 25, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a9c8b3bb-6ad0-4fd2-8bec-d488f13831e5', 'monitoring', 'Monitoring', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a9c8b3bb-6ad0-4fd2-8bec-d488f13831e5', 'backup_system', 'Backup system', 45, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a9c8b3bb-6ad0-4fd2-8bec-d488f13831e5', 'production_deployment', 'Production deployment', 30, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '8975590b-2f04-4fde-beac-57aeaac93cb0', '400fb65c-a931-463f-a627-d1b0f04d8698', 'web_app', 'maintenance', 13, 'Want ongoing support after launch?', '30 days of post-launch support is included either way.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8975590b-2f04-4fde-beac-57aeaac93cb0', 'none', 'Just the 30-day post-launch support (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8975590b-2f04-4fde-beac-57aeaac93cb0', 'monthly', 'Monthly maintenance — €30/month', 30, null, 'per_month', null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8975590b-2f04-4fde-beac-57aeaac93cb0', 'full', 'Full maintenance package — €90/month', 90, null, 'per_month', null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'b70bb711-2734-4582-b20f-6a9baf44973f', '400fb65c-a931-463f-a627-d1b0f04d8698', 'web_app', 'custom_note', 14, 'Anything else we should know?', 'Optional. If it doesn''t fit the options above, describe it and we''ll follow up with a custom quote.', 'text', 'note', null, null, null, null, true
);
