-- Auto-generated by scripts/gen-catalogue-seed.ts from
-- apps/studio/lib/catalogue/{catalogue,shared}.ts — do not hand-edit.

insert into public.catalogue_project_types (version_id, type_id, label, helper, type_order, base_price)
values ('400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_application', 'AI Application', 'A product built around an AI capability.', 7, 590);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '46a1251b-2f5f-4e6a-9e10-05c6cd532852', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_application', 'ai_type', 1, 'What type of AI system are you building?', null, 'single', 'addon', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '46a1251b-2f5f-4e6a-9e10-05c6cd532852', 'ai_chatbot', 'AI chatbot', 0, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '46a1251b-2f5f-4e6a-9e10-05c6cd532852', 'ai_customer_support', 'AI customer support', 0, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '46a1251b-2f5f-4e6a-9e10-05c6cd532852', 'ai_content_generator', 'AI content generator', 0, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '46a1251b-2f5f-4e6a-9e10-05c6cd532852', 'ai_image_generator', 'AI image generator', 0, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '46a1251b-2f5f-4e6a-9e10-05c6cd532852', 'ai_voice_system', 'AI voice system', 0, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '46a1251b-2f5f-4e6a-9e10-05c6cd532852', 'ai_transcription_system', 'AI transcription system', 0, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '46a1251b-2f5f-4e6a-9e10-05c6cd532852', 'ai_document_analysis', 'AI document analysis', 0, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '46a1251b-2f5f-4e6a-9e10-05c6cd532852', 'ai_recommendation_system', 'AI recommendation system', 0, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '46a1251b-2f5f-4e6a-9e10-05c6cd532852', 'ai_search', 'AI search', 0, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '46a1251b-2f5f-4e6a-9e10-05c6cd532852', 'ai_personalization', 'AI personalization', 0, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '46a1251b-2f5f-4e6a-9e10-05c6cd532852', 'ai_knowledge_assistant', 'AI knowledge assistant', 0, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '46a1251b-2f5f-4e6a-9e10-05c6cd532852', 'ai_analytics', 'AI analytics', 0, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '46a1251b-2f5f-4e6a-9e10-05c6cd532852', 'custom_ai_application', 'Custom AI application', 0, null, null, null, false, 13
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '8c83b51e-8d7b-4776-b804-450dcfca69da', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_application', 'ai_data', 2, 'What should the AI work with?', null, 'multi', 'addon', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8c83b51e-8d7b-4776-b804-450dcfca69da', 'text', 'Text', 0, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8c83b51e-8d7b-4776-b804-450dcfca69da', 'images', 'Images', 0, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8c83b51e-8d7b-4776-b804-450dcfca69da', 'audio', 'Audio', 0, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8c83b51e-8d7b-4776-b804-450dcfca69da', 'video', 'Video', 0, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8c83b51e-8d7b-4776-b804-450dcfca69da', 'documents', 'Documents', 0, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8c83b51e-8d7b-4776-b804-450dcfca69da', 'structured_data', 'Structured data', 0, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8c83b51e-8d7b-4776-b804-450dcfca69da', 'website_content', 'Website content', 0, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8c83b51e-8d7b-4776-b804-450dcfca69da', 'database_data', 'Database data', 0, null, null, null, false, 8
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '0c13836a-17ce-4ade-937b-659ae43338ee', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_application', 'ai_features', 3, 'Should your AI remember and search through your own documents and knowledge?', 'Pick everything that applies — this determines the AI infrastructure we build.', 'multi', 'addon', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0c13836a-17ce-4ade-937b-659ae43338ee', 'ai_chatbot', 'AI chatbot', 120, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0c13836a-17ce-4ade-937b-659ae43338ee', 'ai_customer_support', 'AI customer support', 120, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0c13836a-17ce-4ade-937b-659ae43338ee', 'ai_content_generation', 'AI content generation', 90, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0c13836a-17ce-4ade-937b-659ae43338ee', 'ai_image_generation', 'AI image generation', 120, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0c13836a-17ce-4ade-937b-659ae43338ee', 'ai_voice_generation', 'AI voice generation', 120, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0c13836a-17ce-4ade-937b-659ae43338ee', 'ai_transcription', 'AI transcription', 90, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0c13836a-17ce-4ade-937b-659ae43338ee', 'ai_document_analysis', 'AI document analysis', 120, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0c13836a-17ce-4ade-937b-659ae43338ee', 'ai_recommendation', 'AI recommendation system', 145, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0c13836a-17ce-4ade-937b-659ae43338ee', 'ai_search', 'AI search', 120, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0c13836a-17ce-4ade-937b-659ae43338ee', 'ai_personalization', 'AI personalization', 145, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0c13836a-17ce-4ade-937b-659ae43338ee', 'ai_api_integration', 'AI API integration', 90, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0c13836a-17ce-4ade-937b-659ae43338ee', 'custom_ai_model', 'Custom AI model integration', 235, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0c13836a-17ce-4ade-937b-659ae43338ee', 'rag_knowledge_base', 'RAG / knowledge base (remembers your documents)', 175, null, null, null, false, 13
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0c13836a-17ce-4ade-937b-659ae43338ee', 'vector_database', 'Vector database', 90, null, null, null, false, 14
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0c13836a-17ce-4ade-937b-659ae43338ee', 'ai_moderation', 'AI moderation', 90, null, null, null, false, 15
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '64e02027-fe74-4e93-9d90-96f3694b9e13', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_application', 'backend', 4, 'Any backend requirements?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '64e02027-fe74-4e93-9d90-96f3694b9e13', 'custom_database', 'Custom database architecture', 90, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '64e02027-fe74-4e93-9d90-96f3694b9e13', 'rest_api', 'REST API', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '64e02027-fe74-4e93-9d90-96f3694b9e13', 'graphql_api', 'GraphQL API', 120, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '64e02027-fe74-4e93-9d90-96f3694b9e13', 'webhooks', 'Webhooks', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '64e02027-fe74-4e93-9d90-96f3694b9e13', 'realtime', 'Real-time functionality', 90, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '64e02027-fe74-4e93-9d90-96f3694b9e13', 'file_storage', 'File storage', 45, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '64e02027-fe74-4e93-9d90-96f3694b9e13', 'background_jobs', 'Background jobs', 60, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '64e02027-fe74-4e93-9d90-96f3694b9e13', 'automated_processing', 'Automated processing', 75, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '64e02027-fe74-4e93-9d90-96f3694b9e13', 'advanced_backend_logic', 'Advanced backend logic', 120, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '251f98b3-e804-4595-b2d6-b005c17d4da5', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_application', 'auth_security', 5, 'How should people log in, and how secure should it be?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '251f98b3-e804-4595-b2d6-b005c17d4da5', 'email_auth', 'Email + password login', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '251f98b3-e804-4595-b2d6-b005c17d4da5', 'google_login', 'Google login', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '251f98b3-e804-4595-b2d6-b005c17d4da5', 'apple_login', 'Apple login', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '251f98b3-e804-4595-b2d6-b005c17d4da5', 'social_login', 'Other social login', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '251f98b3-e804-4595-b2d6-b005c17d4da5', 'two_factor', 'Two-factor authentication', 45, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '251f98b3-e804-4595-b2d6-b005c17d4da5', 'otp', 'OTP verification', 30, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '251f98b3-e804-4595-b2d6-b005c17d4da5', 'phone_verification', 'Phone verification', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '251f98b3-e804-4595-b2d6-b005c17d4da5', 'role_based_access', 'Role-based access', 45, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '251f98b3-e804-4595-b2d6-b005c17d4da5', 'advanced_security', 'Advanced security configuration', 60, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '251f98b3-e804-4595-b2d6-b005c17d4da5', 'security_audit', 'Security audit', 90, null, null, null, false, 10
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_application', 'design', 6, 'How should it look?', 'A standard design system is included — pick anything beyond that.', 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'custom_ui', 'Custom UI design', 60, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'premium_ui', 'Premium UI/UX', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'figma_first', 'Design mockups before development (Figma)', 60, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'custom_typography', 'Custom typography', 18, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'custom_color', 'Custom color system', 15, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'custom_icons', 'Custom iconography', 25, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'custom_illustrations', 'Custom illustrations', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'custom_graphics', 'Custom graphics', 25, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'custom_3d', 'Custom 3D elements', 60, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'interactive_ui', 'Interactive UI', 60, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'micro_interactions', 'Advanced micro-interactions', 45, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'parallax', 'Parallax effects', 25, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'scroll_animations', 'Scroll animations', 30, null, null, null, false, 13
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'page_transitions', 'Page transition animations', 30, null, null, null, false, 14
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'custom_animation', 'Custom animation', 60, null, null, null, false, 15
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'video_backgrounds', 'Video backgrounds', 30, null, null, null, false, 16
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'advanced_visual_effects', 'Advanced visual effects', 60, null, null, null, false, 17
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '5f1987f5-71ce-40a0-85c3-5e2f505a8d92', 'accessibility', 'Accessibility optimization', 45, null, null, null, false, 18
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'd50248da-c870-4174-9770-9e7f47144800', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_application', 'integrations', 7, 'Anything this should connect to?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd50248da-c870-4174-9770-9e7f47144800', 'google_services', 'Google services', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd50248da-c870-4174-9770-9e7f47144800', 'google_maps', 'Google Maps', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd50248da-c870-4174-9770-9e7f47144800', 'google_analytics', 'Google Analytics', 18, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd50248da-c870-4174-9770-9e7f47144800', 'meta_instagram', 'Meta / Instagram', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd50248da-c870-4174-9770-9e7f47144800', 'tiktok', 'TikTok', 45, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd50248da-c870-4174-9770-9e7f47144800', 'whatsapp_integration', 'WhatsApp', 60, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd50248da-c870-4174-9770-9e7f47144800', 'mailchimp', 'Mailchimp', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd50248da-c870-4174-9770-9e7f47144800', 'hubspot', 'HubSpot', 60, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd50248da-c870-4174-9770-9e7f47144800', 'salesforce', 'Salesforce', 90, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd50248da-c870-4174-9770-9e7f47144800', 'slack', 'Slack', 30, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd50248da-c870-4174-9770-9e7f47144800', 'custom_api_integration', 'Custom API', 90, null, null, null, false, 11
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '8356f90e-ad7c-4ded-8667-d46d6daacf76', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_application', 'revisions', 8, 'How many rounds of revisions do you want?', '2 rounds are included.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8356f90e-ad7c-4ded-8667-d46d6daacf76', 'included', '2 rounds (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8356f90e-ad7c-4ded-8667-d46d6daacf76', 'three', '3 rounds', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8356f90e-ad7c-4ded-8667-d46d6daacf76', 'four', '4 rounds', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8356f90e-ad7c-4ded-8667-d46d6daacf76', 'five', '5 rounds', 60, null, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '6ca072c9-491d-4681-897b-307cdd28dbc6', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_application', 'complexity', 9, 'How complex is this, realistically?', 'This adjusts the whole project price to reflect the extra work.', 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6ca072c9-491d-4681-897b-307cdd28dbc6', 'standard', 'Standard — normal functionality', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6ca072c9-491d-4681-897b-307cdd28dbc6', 'advanced', 'Advanced — more custom UI, logic, or integrations', null, 1.2, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6ca072c9-491d-4681-897b-307cdd28dbc6', 'complex', 'Complex — substantial custom functionality, multiple integrations', null, 1.4, null, null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'e71ead2f-4be7-46ce-bec6-751b947b4879', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_application', 'delivery', 10, 'How quickly do you need it?', null, 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e71ead2f-4be7-46ce-bec6-751b947b4879', 'standard', 'Standard', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e71ead2f-4be7-46ce-bec6-751b947b4879', 'priority', 'Priority (+15%)', null, 1.15, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e71ead2f-4be7-46ce-bec6-751b947b4879', 'rush', 'Rush (+30%)', null, 1.3, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'e71ead2f-4be7-46ce-bec6-751b947b4879', 'emergency', 'Emergency (+50%)', null, 1.5, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '28c7b707-b27f-45f5-98a1-7a02e34ffbe2', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_application', 'hosting', 11, 'Do you need hosting and infrastructure set up?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '28c7b707-b27f-45f5-98a1-7a02e34ffbe2', 'hosting_setup', 'Hosting setup', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '28c7b707-b27f-45f5-98a1-7a02e34ffbe2', 'domain_setup', 'Domain setup', 12, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '28c7b707-b27f-45f5-98a1-7a02e34ffbe2', 'cdn_setup', 'CDN setup', 30, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '28c7b707-b27f-45f5-98a1-7a02e34ffbe2', 'database_hosting', 'Database hosting setup', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '28c7b707-b27f-45f5-98a1-7a02e34ffbe2', 'file_storage_setup', 'File storage setup', 25, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '28c7b707-b27f-45f5-98a1-7a02e34ffbe2', 'email_service_setup', 'Email service setup', 25, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '28c7b707-b27f-45f5-98a1-7a02e34ffbe2', 'monitoring', 'Monitoring', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '28c7b707-b27f-45f5-98a1-7a02e34ffbe2', 'backup_system', 'Backup system', 45, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '28c7b707-b27f-45f5-98a1-7a02e34ffbe2', 'production_deployment', 'Production deployment', 30, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '46f4cc39-a04a-42be-8cc5-8ae211b5d76d', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_application', 'maintenance', 12, 'Want ongoing support after launch?', '30 days of post-launch support is included either way.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '46f4cc39-a04a-42be-8cc5-8ae211b5d76d', 'none', 'Just the 30-day post-launch support (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '46f4cc39-a04a-42be-8cc5-8ae211b5d76d', 'monthly', 'Monthly maintenance — €30/month', 30, null, 'per_month', null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '46f4cc39-a04a-42be-8cc5-8ae211b5d76d', 'full', 'Full maintenance package — €90/month', 90, null, 'per_month', null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'efcf0b25-63e6-4850-9ed3-6f64a009af09', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_application', 'custom_note', 13, 'Anything else we should know?', 'Optional. If it doesn''t fit the options above, describe it and we''ll follow up with a custom quote.', 'text', 'note', null, null, null, null, true
);
