-- Auto-generated by scripts/gen-catalogue-seed.ts from
-- apps/studio/lib/catalogue/{catalogue,shared}.ts — do not hand-edit.

insert into public.catalogue_project_types (version_id, type_id, label, helper, type_order, base_price)
values ('400fb65c-a931-463f-a627-d1b0f04d8698', 'automation', 'Automation System', 'Connects tools and removes manual work.', 9, 235);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '1c2d8475-5f76-4ae5-889b-d679de00cd4b', '400fb65c-a931-463f-a627-d1b0f04d8698', 'automation', 'automation_what', 1, 'What do you want to automate?', null, 'multi', 'addon', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1c2d8475-5f76-4ae5-889b-d679de00cd4b', 'lead_generation', 'Lead generation', 0, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1c2d8475-5f76-4ae5-889b-d679de00cd4b', 'customer_onboarding', 'Customer onboarding', 0, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1c2d8475-5f76-4ae5-889b-d679de00cd4b', 'email', 'Email', 0, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1c2d8475-5f76-4ae5-889b-d679de00cd4b', 'whatsapp', 'WhatsApp', 0, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1c2d8475-5f76-4ae5-889b-d679de00cd4b', 'sales', 'Sales', 0, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1c2d8475-5f76-4ae5-889b-d679de00cd4b', 'payments', 'Payments', 0, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1c2d8475-5f76-4ae5-889b-d679de00cd4b', 'invoices', 'Invoices', 0, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1c2d8475-5f76-4ae5-889b-d679de00cd4b', 'crm', 'CRM', 0, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1c2d8475-5f76-4ae5-889b-d679de00cd4b', 'data_processing', 'Data processing', 0, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1c2d8475-5f76-4ae5-889b-d679de00cd4b', 'reporting', 'Reporting', 0, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1c2d8475-5f76-4ae5-889b-d679de00cd4b', 'internal_workflows', 'Internal workflows', 0, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1c2d8475-5f76-4ae5-889b-d679de00cd4b', 'social_media', 'Social media', 0, null, null, null, false, 12
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '013cd462-a0e8-4856-b160-0a0d1cf642fa', '400fb65c-a931-463f-a627-d1b0f04d8698', 'automation', 'automation_trigger', 2, 'What should start it?', null, 'single', 'addon', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '013cd462-a0e8-4856-b160-0a0d1cf642fa', 'form_submission', 'Form submission', 0, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '013cd462-a0e8-4856-b160-0a0d1cf642fa', 'payment', 'Payment', 0, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '013cd462-a0e8-4856-b160-0a0d1cf642fa', 'new_customer', 'New customer', 0, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '013cd462-a0e8-4856-b160-0a0d1cf642fa', 'email', 'Email', 0, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '013cd462-a0e8-4856-b160-0a0d1cf642fa', 'schedule', 'Schedule', 0, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '013cd462-a0e8-4856-b160-0a0d1cf642fa', 'database_event', 'Database event', 0, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '013cd462-a0e8-4856-b160-0a0d1cf642fa', 'manual_trigger', 'Manual trigger', 0, null, null, null, false, 7
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'ef80952f-0d53-4c9c-a1ee-c0b918e51226', '400fb65c-a931-463f-a627-d1b0f04d8698', 'automation', 'automation_actions', 3, 'What should happen when it runs?', null, 'multi', 'addon', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef80952f-0d53-4c9c-a1ee-c0b918e51226', 'form_to_email', 'Form → email', 25, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef80952f-0d53-4c9c-a1ee-c0b918e51226', 'form_to_database', 'Form → database', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef80952f-0d53-4c9c-a1ee-c0b918e51226', 'email_automation', 'Automated email sequences', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef80952f-0d53-4c9c-a1ee-c0b918e51226', 'sms_automation', 'SMS automation', 60, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef80952f-0d53-4c9c-a1ee-c0b918e51226', 'whatsapp_automation', 'WhatsApp automation', 90, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef80952f-0d53-4c9c-a1ee-c0b918e51226', 'onboarding_automation', 'Customer onboarding automation', 60, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef80952f-0d53-4c9c-a1ee-c0b918e51226', 'invoice_automation', 'Invoice automation', 45, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef80952f-0d53-4c9c-a1ee-c0b918e51226', 'payment_automation', 'Payment automation', 60, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef80952f-0d53-4c9c-a1ee-c0b918e51226', 'crm_automation', 'CRM automation', 90, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef80952f-0d53-4c9c-a1ee-c0b918e51226', 'lead_automation', 'Lead automation', 75, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef80952f-0d53-4c9c-a1ee-c0b918e51226', 'workflow_automation', 'Multi-step workflow automation', 90, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef80952f-0d53-4c9c-a1ee-c0b918e51226', 'scheduled_tasks_automation', 'Scheduled tasks', 45, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef80952f-0d53-4c9c-a1ee-c0b918e51226', 'third_party_automation', 'Third-party tool automation', 60, null, null, null, false, 13
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'b58e4fdc-bcf7-4762-bda5-4fde53b7f080', '400fb65c-a931-463f-a627-d1b0f04d8698', 'automation', 'integrations', 4, 'Anything this should connect to?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b58e4fdc-bcf7-4762-bda5-4fde53b7f080', 'google_services', 'Google services', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b58e4fdc-bcf7-4762-bda5-4fde53b7f080', 'google_maps', 'Google Maps', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b58e4fdc-bcf7-4762-bda5-4fde53b7f080', 'google_analytics', 'Google Analytics', 18, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b58e4fdc-bcf7-4762-bda5-4fde53b7f080', 'meta_instagram', 'Meta / Instagram', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b58e4fdc-bcf7-4762-bda5-4fde53b7f080', 'tiktok', 'TikTok', 45, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b58e4fdc-bcf7-4762-bda5-4fde53b7f080', 'whatsapp_integration', 'WhatsApp', 60, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b58e4fdc-bcf7-4762-bda5-4fde53b7f080', 'mailchimp', 'Mailchimp', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b58e4fdc-bcf7-4762-bda5-4fde53b7f080', 'hubspot', 'HubSpot', 60, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b58e4fdc-bcf7-4762-bda5-4fde53b7f080', 'salesforce', 'Salesforce', 90, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b58e4fdc-bcf7-4762-bda5-4fde53b7f080', 'slack', 'Slack', 30, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b58e4fdc-bcf7-4762-bda5-4fde53b7f080', 'custom_api_integration', 'Custom API', 90, null, null, null, false, 11
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '4bd8faf8-31a9-4b0f-ad2b-045a5c45e87d', '400fb65c-a931-463f-a627-d1b0f04d8698', 'automation', 'backend', 5, 'Any backend requirements?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4bd8faf8-31a9-4b0f-ad2b-045a5c45e87d', 'custom_database', 'Custom database architecture', 90, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4bd8faf8-31a9-4b0f-ad2b-045a5c45e87d', 'rest_api', 'REST API', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4bd8faf8-31a9-4b0f-ad2b-045a5c45e87d', 'graphql_api', 'GraphQL API', 120, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4bd8faf8-31a9-4b0f-ad2b-045a5c45e87d', 'webhooks', 'Webhooks', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4bd8faf8-31a9-4b0f-ad2b-045a5c45e87d', 'realtime', 'Real-time functionality', 90, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4bd8faf8-31a9-4b0f-ad2b-045a5c45e87d', 'file_storage', 'File storage', 45, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4bd8faf8-31a9-4b0f-ad2b-045a5c45e87d', 'background_jobs', 'Background jobs', 60, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4bd8faf8-31a9-4b0f-ad2b-045a5c45e87d', 'automated_processing', 'Automated processing', 75, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4bd8faf8-31a9-4b0f-ad2b-045a5c45e87d', 'advanced_backend_logic', 'Advanced backend logic', 120, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '7df73a4a-778f-4cc1-a1c5-d5bfee030244', '400fb65c-a931-463f-a627-d1b0f04d8698', 'automation', 'revisions', 6, 'How many rounds of revisions do you want?', '2 rounds are included.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7df73a4a-778f-4cc1-a1c5-d5bfee030244', 'included', '2 rounds (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7df73a4a-778f-4cc1-a1c5-d5bfee030244', 'three', '3 rounds', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7df73a4a-778f-4cc1-a1c5-d5bfee030244', 'four', '4 rounds', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7df73a4a-778f-4cc1-a1c5-d5bfee030244', 'five', '5 rounds', 60, null, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '398065f1-9684-499e-9b64-86d630866cbc', '400fb65c-a931-463f-a627-d1b0f04d8698', 'automation', 'complexity', 7, 'How complex is this, realistically?', 'This adjusts the whole project price to reflect the extra work.', 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '398065f1-9684-499e-9b64-86d630866cbc', 'standard', 'Standard — normal functionality', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '398065f1-9684-499e-9b64-86d630866cbc', 'advanced', 'Advanced — more custom UI, logic, or integrations', null, 1.2, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '398065f1-9684-499e-9b64-86d630866cbc', 'complex', 'Complex — substantial custom functionality, multiple integrations', null, 1.4, null, null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'ef200dc9-265d-4f4f-9412-34b6b7b497aa', '400fb65c-a931-463f-a627-d1b0f04d8698', 'automation', 'delivery', 8, 'How quickly do you need it?', null, 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef200dc9-265d-4f4f-9412-34b6b7b497aa', 'standard', 'Standard', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef200dc9-265d-4f4f-9412-34b6b7b497aa', 'priority', 'Priority (+15%)', null, 1.15, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef200dc9-265d-4f4f-9412-34b6b7b497aa', 'rush', 'Rush (+30%)', null, 1.3, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ef200dc9-265d-4f4f-9412-34b6b7b497aa', 'emergency', 'Emergency (+50%)', null, 1.5, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '88fce75b-94be-424f-ba41-c271f65feb57', '400fb65c-a931-463f-a627-d1b0f04d8698', 'automation', 'hosting', 9, 'Do you need hosting and infrastructure set up?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '88fce75b-94be-424f-ba41-c271f65feb57', 'hosting_setup', 'Hosting setup', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '88fce75b-94be-424f-ba41-c271f65feb57', 'domain_setup', 'Domain setup', 12, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '88fce75b-94be-424f-ba41-c271f65feb57', 'cdn_setup', 'CDN setup', 30, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '88fce75b-94be-424f-ba41-c271f65feb57', 'database_hosting', 'Database hosting setup', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '88fce75b-94be-424f-ba41-c271f65feb57', 'file_storage_setup', 'File storage setup', 25, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '88fce75b-94be-424f-ba41-c271f65feb57', 'email_service_setup', 'Email service setup', 25, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '88fce75b-94be-424f-ba41-c271f65feb57', 'monitoring', 'Monitoring', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '88fce75b-94be-424f-ba41-c271f65feb57', 'backup_system', 'Backup system', 45, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '88fce75b-94be-424f-ba41-c271f65feb57', 'production_deployment', 'Production deployment', 30, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '3bcf75de-b635-477d-856d-44a3f6d2e960', '400fb65c-a931-463f-a627-d1b0f04d8698', 'automation', 'maintenance', 10, 'Want ongoing support after launch?', '30 days of post-launch support is included either way.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '3bcf75de-b635-477d-856d-44a3f6d2e960', 'none', 'Just the 30-day post-launch support (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '3bcf75de-b635-477d-856d-44a3f6d2e960', 'monthly', 'Monthly maintenance — €30/month', 30, null, 'per_month', null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '3bcf75de-b635-477d-856d-44a3f6d2e960', 'full', 'Full maintenance package — €90/month', 90, null, 'per_month', null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '0c00cf06-3f61-4bd4-9978-0f77579f85b8', '400fb65c-a931-463f-a627-d1b0f04d8698', 'automation', 'custom_note', 11, 'Anything else we should know?', 'Optional. If it doesn''t fit the options above, describe it and we''ll follow up with a custom quote.', 'text', 'note', null, null, null, null, true
);
