-- Auto-generated by scripts/gen-catalogue-seed.ts from
-- apps/studio/lib/catalogue/{catalogue,shared}.ts — do not hand-edit.

insert into public.catalogue_project_types (version_id, type_id, label, helper, type_order, base_price)
values ('400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'Website', 'A site to inform, showcase, or sell.', 1, null);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '8db296e3-2458-4179-81d9-a37a1bed5672', '400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'website_base', 1, 'How big is it?', null, 'single', 'base', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8db296e3-2458-4179-81d9-a37a1bed5672', 'landing_page', 'Landing page (1 page)', 90, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8db296e3-2458-4179-81d9-a37a1bed5672', 'one_page', 'One-page website', 105, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '8db296e3-2458-4179-81d9-a37a1bed5672', 'multi_page', 'Multi-page website', 235, null, null, 'Includes up to 5 pages.', false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'dd5121de-662a-4e11-b625-f90fe74bfff8', '400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'website_kind', 2, 'What kind of website is it?', 'This doesn''t change the price — it just helps us understand the project.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dd5121de-662a-4e11-b625-f90fe74bfff8', 'personal', 'Personal', 0, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dd5121de-662a-4e11-b625-f90fe74bfff8', 'portfolio', 'Portfolio', 0, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dd5121de-662a-4e11-b625-f90fe74bfff8', 'business', 'Business', 0, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dd5121de-662a-4e11-b625-f90fe74bfff8', 'corporate', 'Corporate', 0, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dd5121de-662a-4e11-b625-f90fe74bfff8', 'blog', 'Blog', 0, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dd5121de-662a-4e11-b625-f90fe74bfff8', 'news_media', 'News / media', 0, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dd5121de-662a-4e11-b625-f90fe74bfff8', 'restaurant', 'Restaurant', 0, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dd5121de-662a-4e11-b625-f90fe74bfff8', 'agency', 'Agency', 0, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dd5121de-662a-4e11-b625-f90fe74bfff8', 'booking', 'Booking', 0, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dd5121de-662a-4e11-b625-f90fe74bfff8', 'membership', 'Membership', 0, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dd5121de-662a-4e11-b625-f90fe74bfff8', 'other', 'Other', 0, null, null, null, false, 11
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'e9d255fb-7410-4466-8d57-aea126f2729e', '400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'website_structure', 3, 'How many additional pages beyond what''s included?', null, 'number', 'addon', 0, 40, 20, null, true
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '29e0300c-20f1-429d-9865-11f78833e61f', '400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'website_sections', 4, 'Any specific sections or pages?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '29e0300c-20f1-429d-9865-11f78833e61f', 'blog_section', 'Blog', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '29e0300c-20f1-429d-9865-11f78833e61f', 'portfolio_section', 'Portfolio', 25, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '29e0300c-20f1-429d-9865-11f78833e61f', 'faq', 'FAQ section', 12, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '29e0300c-20f1-429d-9865-11f78833e61f', 'testimonials', 'Testimonials section', 12, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '29e0300c-20f1-429d-9865-11f78833e61f', 'pricing_section', 'Pricing section', 15, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '29e0300c-20f1-429d-9865-11f78833e61f', 'team_section', 'Team section', 15, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '29e0300c-20f1-429d-9865-11f78833e61f', 'careers', 'Careers page', 25, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '29e0300c-20f1-429d-9865-11f78833e61f', 'resources', 'Resources section', 30, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '29e0300c-20f1-429d-9865-11f78833e61f', 'documentation', 'Documentation section', 45, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '29e0300c-20f1-429d-9865-11f78833e61f', 'multi_language', 'Multi-language support', 60, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '29e0300c-20f1-429d-9865-11f78833e61f', 'custom_nav', 'Custom navigation structure', 30, null, null, null, false, 11
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', '400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'design', 5, 'How should it look?', 'A standard design system is included — pick anything beyond that.', 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'custom_ui', 'Custom UI design', 60, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'premium_ui', 'Premium UI/UX', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'figma_first', 'Design mockups before development (Figma)', 60, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'custom_typography', 'Custom typography', 18, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'custom_color', 'Custom color system', 15, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'custom_icons', 'Custom iconography', 25, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'custom_illustrations', 'Custom illustrations', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'custom_graphics', 'Custom graphics', 25, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'custom_3d', 'Custom 3D elements', 60, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'interactive_ui', 'Interactive UI', 60, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'micro_interactions', 'Advanced micro-interactions', 45, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'parallax', 'Parallax effects', 25, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'scroll_animations', 'Scroll animations', 30, null, null, null, false, 13
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'page_transitions', 'Page transition animations', 30, null, null, null, false, 14
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'custom_animation', 'Custom animation', 60, null, null, null, false, 15
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'video_backgrounds', 'Video backgrounds', 30, null, null, null, false, 16
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'advanced_visual_effects', 'Advanced visual effects', 60, null, null, null, false, 17
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '94030ccf-a903-412c-abd9-56378a56c96c', 'accessibility', 'Accessibility optimization', 45, null, null, null, false, 18
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', '400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'website_functionality', 6, 'What should it do?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', 'contact_form', 'Contact form', 12, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', 'newsletter', 'Newsletter signup', 15, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', 'search', 'Search', 25, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', 'advanced_search', 'Advanced search / filtering', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', 'user_accounts', 'User accounts', 60, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', 'user_dashboard', 'User dashboard', 90, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', 'notifications', 'Notifications', 45, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', 'favorites', 'Favorites / wishlist', 30, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', 'reviews', 'Reviews / ratings', 35, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', 'file_upload', 'File upload', 30, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', 'booking', 'Booking system', 60, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', 'appointments', 'Appointment scheduling', 60, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', 'membership', 'Membership system', 90, null, null, null, false, 13
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', 'subscriptions', 'Subscription system', 90, null, null, null, false, 14
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', 'coupons', 'Coupon / discount system', 30, null, null, null, false, 15
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '10a82c6f-badd-43ec-8354-b9fd32102f38', 'loyalty', 'Loyalty / rewards system', 90, null, null, null, false, 16
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '1e0c5825-1900-49ab-ae7d-357f8a1384d3', '400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'cms_admin', 7, 'Do you need a way to manage content or the business yourself?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1e0c5825-1900-49ab-ae7d-357f8a1384d3', 'basic_cms', 'Basic content management', 60, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1e0c5825-1900-49ab-ae7d-357f8a1384d3', 'admin_dashboard', 'Admin dashboard', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1e0c5825-1900-49ab-ae7d-357f8a1384d3', 'custom_admin_dashboard', 'Custom-built admin dashboard', 145, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1e0c5825-1900-49ab-ae7d-357f8a1384d3', 'user_management', 'User management', 60, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1e0c5825-1900-49ab-ae7d-357f8a1384d3', 'order_management', 'Order management', 60, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1e0c5825-1900-49ab-ae7d-357f8a1384d3', 'customer_management', 'Customer management', 60, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1e0c5825-1900-49ab-ae7d-357f8a1384d3', 'analytics_dashboard', 'Analytics dashboard', 75, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1e0c5825-1900-49ab-ae7d-357f8a1384d3', 'role_permissions', 'Different permissions for different users', 60, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1e0c5825-1900-49ab-ae7d-357f8a1384d3', 'multiple_admin_accounts', 'Multiple admin accounts', 30, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1e0c5825-1900-49ab-ae7d-357f8a1384d3', 'activity_logs', 'Activity logs', 45, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1e0c5825-1900-49ab-ae7d-357f8a1384d3', 'automated_reports', 'Automated reports', 60, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1e0c5825-1900-49ab-ae7d-357f8a1384d3', 'export_data', 'Export data', 25, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '1e0c5825-1900-49ab-ae7d-357f8a1384d3', 'import_data', 'Import data', 30, null, null, null, false, 13
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'aa16c587-f54a-4bbd-97f1-ee07e018b5ae', '400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'payments', 8, 'How should people pay?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa16c587-f54a-4bbd-97f1-ee07e018b5ae', 'payment_gateway_integration', 'Payment integration', 45, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa16c587-f54a-4bbd-97f1-ee07e018b5ae', 'card_payments', 'Card payments', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa16c587-f54a-4bbd-97f1-ee07e018b5ae', 'bank_transfer', 'Bank transfer', 25, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa16c587-f54a-4bbd-97f1-ee07e018b5ae', 'mobile_money', 'Mobile money', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa16c587-f54a-4bbd-97f1-ee07e018b5ae', 'multiple_currencies', 'Multiple currencies', 60, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa16c587-f54a-4bbd-97f1-ee07e018b5ae', 'recurring_payments', 'Recurring / subscription billing', 75, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa16c587-f54a-4bbd-97f1-ee07e018b5ae', 'automatic_invoices', 'Automatic invoices', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa16c587-f54a-4bbd-97f1-ee07e018b5ae', 'payment_receipts', 'Payment receipts', 18, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa16c587-f54a-4bbd-97f1-ee07e018b5ae', 'refund_system', 'Refund system', 30, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa16c587-f54a-4bbd-97f1-ee07e018b5ae', 'split_payments', 'Split payments', 60, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa16c587-f54a-4bbd-97f1-ee07e018b5ae', 'marketplace_payments', 'Marketplace payments (pay out multiple parties)', 120, null, null, null, false, 11
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '30389418-7eef-41e0-b9f9-1e721b724b27', '400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'integrations', 9, 'Anything this should connect to?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '30389418-7eef-41e0-b9f9-1e721b724b27', 'google_services', 'Google services', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '30389418-7eef-41e0-b9f9-1e721b724b27', 'google_maps', 'Google Maps', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '30389418-7eef-41e0-b9f9-1e721b724b27', 'google_analytics', 'Google Analytics', 18, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '30389418-7eef-41e0-b9f9-1e721b724b27', 'meta_instagram', 'Meta / Instagram', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '30389418-7eef-41e0-b9f9-1e721b724b27', 'tiktok', 'TikTok', 45, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '30389418-7eef-41e0-b9f9-1e721b724b27', 'whatsapp_integration', 'WhatsApp', 60, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '30389418-7eef-41e0-b9f9-1e721b724b27', 'mailchimp', 'Mailchimp', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '30389418-7eef-41e0-b9f9-1e721b724b27', 'hubspot', 'HubSpot', 60, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '30389418-7eef-41e0-b9f9-1e721b724b27', 'salesforce', 'Salesforce', 90, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '30389418-7eef-41e0-b9f9-1e721b724b27', 'slack', 'Slack', 30, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '30389418-7eef-41e0-b9f9-1e721b724b27', 'custom_api_integration', 'Custom API', 90, null, null, null, false, 11
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'd125ba53-7bbf-46e6-9cc8-b1b29b64031e', '400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'content', 10, 'Do you need us to write or produce content too?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd125ba53-7bbf-46e6-9cc8-b1b29b64031e', 'copywriting', 'Copywriting', 45, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd125ba53-7bbf-46e6-9cc8-b1b29b64031e', 'website_copy', 'Website copy', 45, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd125ba53-7bbf-46e6-9cc8-b1b29b64031e', 'image_sourcing', 'Image sourcing', 18, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd125ba53-7bbf-46e6-9cc8-b1b29b64031e', 'video_editing', 'Video editing', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd125ba53-7bbf-46e6-9cc8-b1b29b64031e', 'promo_video', 'Promotional video', 60, null, null, null, false, 5
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '6f4a9a76-6472-4e24-84b5-4ff6b7710c45', '400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'revisions', 11, 'How many rounds of revisions do you want?', '2 rounds are included.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6f4a9a76-6472-4e24-84b5-4ff6b7710c45', 'included', '2 rounds (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6f4a9a76-6472-4e24-84b5-4ff6b7710c45', 'three', '3 rounds', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6f4a9a76-6472-4e24-84b5-4ff6b7710c45', 'four', '4 rounds', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '6f4a9a76-6472-4e24-84b5-4ff6b7710c45', 'five', '5 rounds', 60, null, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '0ea80ea9-2671-465f-a710-03afc7cd4c21', '400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'complexity', 12, 'How complex is this, realistically?', 'This adjusts the whole project price to reflect the extra work.', 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0ea80ea9-2671-465f-a710-03afc7cd4c21', 'standard', 'Standard — normal functionality', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0ea80ea9-2671-465f-a710-03afc7cd4c21', 'advanced', 'Advanced — more custom UI, logic, or integrations', null, 1.2, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0ea80ea9-2671-465f-a710-03afc7cd4c21', 'complex', 'Complex — substantial custom functionality, multiple integrations', null, 1.4, null, null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '381eff41-916c-4df7-aa6c-f455aeff93a1', '400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'delivery', 13, 'How quickly do you need it?', null, 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '381eff41-916c-4df7-aa6c-f455aeff93a1', 'standard', 'Standard', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '381eff41-916c-4df7-aa6c-f455aeff93a1', 'priority', 'Priority (+15%)', null, 1.15, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '381eff41-916c-4df7-aa6c-f455aeff93a1', 'rush', 'Rush (+30%)', null, 1.3, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '381eff41-916c-4df7-aa6c-f455aeff93a1', 'emergency', 'Emergency (+50%)', null, 1.5, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '9a20cacf-4252-406d-b4c5-8c07ac200772', '400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'hosting', 14, 'Do you need hosting and infrastructure set up?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9a20cacf-4252-406d-b4c5-8c07ac200772', 'hosting_setup', 'Hosting setup', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9a20cacf-4252-406d-b4c5-8c07ac200772', 'domain_setup', 'Domain setup', 12, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9a20cacf-4252-406d-b4c5-8c07ac200772', 'cdn_setup', 'CDN setup', 30, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9a20cacf-4252-406d-b4c5-8c07ac200772', 'database_hosting', 'Database hosting setup', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9a20cacf-4252-406d-b4c5-8c07ac200772', 'file_storage_setup', 'File storage setup', 25, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9a20cacf-4252-406d-b4c5-8c07ac200772', 'email_service_setup', 'Email service setup', 25, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9a20cacf-4252-406d-b4c5-8c07ac200772', 'monitoring', 'Monitoring', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9a20cacf-4252-406d-b4c5-8c07ac200772', 'backup_system', 'Backup system', 45, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9a20cacf-4252-406d-b4c5-8c07ac200772', 'production_deployment', 'Production deployment', 30, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '984a217e-41e4-496e-9bbd-2c002970b6d7', '400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'maintenance', 15, 'Want ongoing support after launch?', '30 days of post-launch support is included either way.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '984a217e-41e4-496e-9bbd-2c002970b6d7', 'none', 'Just the 30-day post-launch support (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '984a217e-41e4-496e-9bbd-2c002970b6d7', 'monthly', 'Monthly maintenance — €30/month', 30, null, 'per_month', null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '984a217e-41e4-496e-9bbd-2c002970b6d7', 'full', 'Full maintenance package — €90/month', 90, null, 'per_month', null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '071574a9-4a5e-4a85-a6d3-3bb99f248c0f', '400fb65c-a931-463f-a627-d1b0f04d8698', 'website', 'custom_note', 16, 'Anything else we should know?', 'Optional. If it doesn''t fit the options above, describe it and we''ll follow up with a custom quote.', 'text', 'note', null, null, null, null, true
);
