-- Auto-generated by scripts/gen-catalogue-seed.ts from
-- apps/studio/lib/catalogue/{catalogue,shared}.ts — do not hand-edit.

insert into public.catalogue_project_types (version_id, type_id, label, helper, type_order, base_price)
values ('400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_agent', 'AI Agent', 'An AI that takes actions on your behalf.', 8, 350);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'bc551266-12a8-446b-9c32-2deab2412e4c', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_agent', 'agent_purpose', 1, 'What should the agent do?', null, 'single', 'addon', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'bc551266-12a8-446b-9c32-2deab2412e4c', 'customer_support', 'Customer support', 0, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'bc551266-12a8-446b-9c32-2deab2412e4c', 'sales', 'Sales', 0, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'bc551266-12a8-446b-9c32-2deab2412e4c', 'lead_generation', 'Lead generation', 0, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'bc551266-12a8-446b-9c32-2deab2412e4c', 'research', 'Research', 0, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'bc551266-12a8-446b-9c32-2deab2412e4c', 'data_analysis', 'Data analysis', 0, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'bc551266-12a8-446b-9c32-2deab2412e4c', 'personal_assistant', 'Personal assistant', 0, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'bc551266-12a8-446b-9c32-2deab2412e4c', 'business_operations', 'Business operations', 0, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'bc551266-12a8-446b-9c32-2deab2412e4c', 'content_creation', 'Content creation', 0, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'bc551266-12a8-446b-9c32-2deab2412e4c', 'scheduling', 'Scheduling', 0, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'bc551266-12a8-446b-9c32-2deab2412e4c', 'customer_onboarding', 'Customer onboarding', 0, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'bc551266-12a8-446b-9c32-2deab2412e4c', 'internal_company_tasks', 'Internal company tasks', 0, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'bc551266-12a8-446b-9c32-2deab2412e4c', 'other', 'Other', 0, null, null, null, false, 12
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '4155dc7d-1ae2-4449-a262-6f4dff6c79db', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_agent', 'agent_channels', 2, 'Where should the agent operate?', null, 'multi', 'addon', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4155dc7d-1ae2-4449-a262-6f4dff6c79db', 'channel_website', 'Website', 45, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4155dc7d-1ae2-4449-a262-6f4dff6c79db', 'channel_whatsapp', 'WhatsApp', 60, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4155dc7d-1ae2-4449-a262-6f4dff6c79db', 'channel_telegram', 'Telegram', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4155dc7d-1ae2-4449-a262-6f4dff6c79db', 'channel_discord', 'Discord', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4155dc7d-1ae2-4449-a262-6f4dff6c79db', 'channel_slack', 'Slack', 30, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4155dc7d-1ae2-4449-a262-6f4dff6c79db', 'channel_email', 'Email', 45, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4155dc7d-1ae2-4449-a262-6f4dff6c79db', 'channel_dashboard', 'Internal dashboard', 60, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '4155dc7d-1ae2-4449-a262-6f4dff6c79db', 'channel_api', 'API', 45, null, null, null, false, 8
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '44a52efd-76a2-4464-a5ff-1348cce05f80', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_agent', 'agent_access', 3, 'What should the agent be able to access?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '44a52efd-76a2-4464-a5ff-1348cce05f80', 'access_knowledge_base', 'Knowledge base', 175, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '44a52efd-76a2-4464-a5ff-1348cce05f80', 'access_database', 'Your database', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '44a52efd-76a2-4464-a5ff-1348cce05f80', 'access_calendar', 'Calendar', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '44a52efd-76a2-4464-a5ff-1348cce05f80', 'access_email', 'Email', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '44a52efd-76a2-4464-a5ff-1348cce05f80', 'access_apis', 'External APIs', 90, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '44a52efd-76a2-4464-a5ff-1348cce05f80', 'access_web_search', 'Internet / web search', 45, null, null, null, false, 6
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '9c581fc1-f69b-48c5-8d8a-6d83e82de5fd', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_agent', 'agent_actions', 4, 'What actions should it be able to take on its own?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c581fc1-f69b-48c5-8d8a-6d83e82de5fd', 'action_send_emails', 'Send emails', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c581fc1-f69b-48c5-8d8a-6d83e82de5fd', 'action_create_records', 'Create records', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c581fc1-f69b-48c5-8d8a-6d83e82de5fd', 'action_update_records', 'Update records', 30, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c581fc1-f69b-48c5-8d8a-6d83e82de5fd', 'action_search_db', 'Search databases', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c581fc1-f69b-48c5-8d8a-6d83e82de5fd', 'action_book_appointments', 'Book appointments', 45, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c581fc1-f69b-48c5-8d8a-6d83e82de5fd', 'action_generate_documents', 'Generate documents', 45, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c581fc1-f69b-48c5-8d8a-6d83e82de5fd', 'action_api_requests', 'Make API requests', 45, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c581fc1-f69b-48c5-8d8a-6d83e82de5fd', 'action_notifications', 'Send notifications', 30, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '9c581fc1-f69b-48c5-8d8a-6d83e82de5fd', 'action_workflows', 'Execute multi-step workflows', 90, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'b0ffe9b7-0c84-45e0-acc5-0eed8400d6d3', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_agent', 'agent_intelligence', 5, 'How capable should it be?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ffe9b7-0c84-45e0-acc5-0eed8400d6d3', 'multi_agent', 'Multiple agents working together', 350, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ffe9b7-0c84-45e0-acc5-0eed8400d6d3', 'agent_memory', 'Memory across conversations', 60, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ffe9b7-0c84-45e0-acc5-0eed8400d6d3', 'custom_ai_workflow', 'Custom AI workflow', 175, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ffe9b7-0c84-45e0-acc5-0eed8400d6d3', 'vector_database_agent', 'Vector database', 90, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ffe9b7-0c84-45e0-acc5-0eed8400d6d3', 'human_approval', 'Human approval before acting', 45, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b0ffe9b7-0c84-45e0-acc5-0eed8400d6d3', 'scheduled_tasks', 'Scheduled / autonomous tasks', 45, null, null, null, false, 6
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '39f586fc-00d1-4777-9ee3-ff6a6476ea1e', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_agent', 'backend', 6, 'Any backend requirements?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '39f586fc-00d1-4777-9ee3-ff6a6476ea1e', 'custom_database', 'Custom database architecture', 90, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '39f586fc-00d1-4777-9ee3-ff6a6476ea1e', 'rest_api', 'REST API', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '39f586fc-00d1-4777-9ee3-ff6a6476ea1e', 'graphql_api', 'GraphQL API', 120, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '39f586fc-00d1-4777-9ee3-ff6a6476ea1e', 'webhooks', 'Webhooks', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '39f586fc-00d1-4777-9ee3-ff6a6476ea1e', 'realtime', 'Real-time functionality', 90, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '39f586fc-00d1-4777-9ee3-ff6a6476ea1e', 'file_storage', 'File storage', 45, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '39f586fc-00d1-4777-9ee3-ff6a6476ea1e', 'background_jobs', 'Background jobs', 60, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '39f586fc-00d1-4777-9ee3-ff6a6476ea1e', 'automated_processing', 'Automated processing', 75, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '39f586fc-00d1-4777-9ee3-ff6a6476ea1e', 'advanced_backend_logic', 'Advanced backend logic', 120, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_agent', 'design', 7, 'How should it look?', 'A standard design system is included — pick anything beyond that.', 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'custom_ui', 'Custom UI design', 60, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'premium_ui', 'Premium UI/UX', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'figma_first', 'Design mockups before development (Figma)', 60, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'custom_typography', 'Custom typography', 18, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'custom_color', 'Custom color system', 15, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'custom_icons', 'Custom iconography', 25, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'custom_illustrations', 'Custom illustrations', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'custom_graphics', 'Custom graphics', 25, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'custom_3d', 'Custom 3D elements', 60, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'interactive_ui', 'Interactive UI', 60, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'micro_interactions', 'Advanced micro-interactions', 45, null, null, null, false, 11
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'parallax', 'Parallax effects', 25, null, null, null, false, 12
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'scroll_animations', 'Scroll animations', 30, null, null, null, false, 13
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'page_transitions', 'Page transition animations', 30, null, null, null, false, 14
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'custom_animation', 'Custom animation', 60, null, null, null, false, 15
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'video_backgrounds', 'Video backgrounds', 30, null, null, null, false, 16
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'advanced_visual_effects', 'Advanced visual effects', 60, null, null, null, false, 17
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7a682100-45f1-483f-930e-303e15ea2618', 'accessibility', 'Accessibility optimization', 45, null, null, null, false, 18
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'dd1341bb-7a10-4de0-967f-07e73fc83c69', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_agent', 'revisions', 8, 'How many rounds of revisions do you want?', '2 rounds are included.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dd1341bb-7a10-4de0-967f-07e73fc83c69', 'included', '2 rounds (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dd1341bb-7a10-4de0-967f-07e73fc83c69', 'three', '3 rounds', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dd1341bb-7a10-4de0-967f-07e73fc83c69', 'four', '4 rounds', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dd1341bb-7a10-4de0-967f-07e73fc83c69', 'five', '5 rounds', 60, null, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '2195fa33-00e0-4fac-aa8b-7ffb302944aa', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_agent', 'complexity', 9, 'How complex is this, realistically?', 'This adjusts the whole project price to reflect the extra work.', 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '2195fa33-00e0-4fac-aa8b-7ffb302944aa', 'standard', 'Standard — normal functionality', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '2195fa33-00e0-4fac-aa8b-7ffb302944aa', 'advanced', 'Advanced — more custom UI, logic, or integrations', null, 1.2, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '2195fa33-00e0-4fac-aa8b-7ffb302944aa', 'complex', 'Complex — substantial custom functionality, multiple integrations', null, 1.4, null, null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '49e1b4f0-e554-4431-b1cf-c74c8cc7f19d', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_agent', 'delivery', 10, 'How quickly do you need it?', null, 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '49e1b4f0-e554-4431-b1cf-c74c8cc7f19d', 'standard', 'Standard', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '49e1b4f0-e554-4431-b1cf-c74c8cc7f19d', 'priority', 'Priority (+15%)', null, 1.15, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '49e1b4f0-e554-4431-b1cf-c74c8cc7f19d', 'rush', 'Rush (+30%)', null, 1.3, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '49e1b4f0-e554-4431-b1cf-c74c8cc7f19d', 'emergency', 'Emergency (+50%)', null, 1.5, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '0741470a-89db-4aa7-b4ad-5dc336132630', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_agent', 'hosting', 11, 'Do you need hosting and infrastructure set up?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0741470a-89db-4aa7-b4ad-5dc336132630', 'hosting_setup', 'Hosting setup', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0741470a-89db-4aa7-b4ad-5dc336132630', 'domain_setup', 'Domain setup', 12, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0741470a-89db-4aa7-b4ad-5dc336132630', 'cdn_setup', 'CDN setup', 30, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0741470a-89db-4aa7-b4ad-5dc336132630', 'database_hosting', 'Database hosting setup', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0741470a-89db-4aa7-b4ad-5dc336132630', 'file_storage_setup', 'File storage setup', 25, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0741470a-89db-4aa7-b4ad-5dc336132630', 'email_service_setup', 'Email service setup', 25, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0741470a-89db-4aa7-b4ad-5dc336132630', 'monitoring', 'Monitoring', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0741470a-89db-4aa7-b4ad-5dc336132630', 'backup_system', 'Backup system', 45, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '0741470a-89db-4aa7-b4ad-5dc336132630', 'production_deployment', 'Production deployment', 30, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '3785fd68-4f23-4e07-8071-5ef0d2b4d25b', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_agent', 'maintenance', 12, 'Want ongoing support after launch?', '30 days of post-launch support is included either way.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '3785fd68-4f23-4e07-8071-5ef0d2b4d25b', 'none', 'Just the 30-day post-launch support (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '3785fd68-4f23-4e07-8071-5ef0d2b4d25b', 'monthly', 'Monthly maintenance — €30/month', 30, null, 'per_month', null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '3785fd68-4f23-4e07-8071-5ef0d2b4d25b', 'full', 'Full maintenance package — €90/month', 90, null, 'per_month', null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '8b06a614-fa79-47ce-8ca3-9e37eb3b61e9', '400fb65c-a931-463f-a627-d1b0f04d8698', 'ai_agent', 'custom_note', 13, 'Anything else we should know?', 'Optional. If it doesn''t fit the options above, describe it and we''ll follow up with a custom quote.', 'text', 'note', null, null, null, null, true
);
