-- Auto-generated by scripts/gen-catalogue-seed.ts from
-- apps/studio/lib/catalogue/{catalogue,shared}.ts — do not hand-edit.

insert into public.catalogue_project_types (version_id, type_id, label, helper, type_order, base_price)
values ('400fb65c-a931-463f-a627-d1b0f04d8698', 'api_backend', 'API / Backend System', 'Infrastructure with no client-facing UI.', 10, 350);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'ded0fd6c-77a4-4a1f-bb68-6a52547cbcc8', '400fb65c-a931-463f-a627-d1b0f04d8698', 'api_backend', 'api_type', 1, 'What should this power?', 'No client-facing pages here — this is infrastructure.', 'text', 'addon', null, null, null, null, true
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'd21d44ab-518b-4af3-bba2-19e649ca10e3', '400fb65c-a931-463f-a627-d1b0f04d8698', 'api_backend', 'backend', 2, 'Any backend requirements?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd21d44ab-518b-4af3-bba2-19e649ca10e3', 'custom_database', 'Custom database architecture', 90, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd21d44ab-518b-4af3-bba2-19e649ca10e3', 'rest_api', 'REST API', 90, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd21d44ab-518b-4af3-bba2-19e649ca10e3', 'graphql_api', 'GraphQL API', 120, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd21d44ab-518b-4af3-bba2-19e649ca10e3', 'webhooks', 'Webhooks', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd21d44ab-518b-4af3-bba2-19e649ca10e3', 'realtime', 'Real-time functionality', 90, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd21d44ab-518b-4af3-bba2-19e649ca10e3', 'file_storage', 'File storage', 45, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd21d44ab-518b-4af3-bba2-19e649ca10e3', 'background_jobs', 'Background jobs', 60, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd21d44ab-518b-4af3-bba2-19e649ca10e3', 'automated_processing', 'Automated processing', 75, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'd21d44ab-518b-4af3-bba2-19e649ca10e3', 'advanced_backend_logic', 'Advanced backend logic', 120, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'aa1cff36-2b13-4c3b-b9a0-fe0011356e1b', '400fb65c-a931-463f-a627-d1b0f04d8698', 'api_backend', 'auth_security', 3, 'How should people log in, and how secure should it be?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa1cff36-2b13-4c3b-b9a0-fe0011356e1b', 'email_auth', 'Email + password login', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa1cff36-2b13-4c3b-b9a0-fe0011356e1b', 'google_login', 'Google login', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa1cff36-2b13-4c3b-b9a0-fe0011356e1b', 'apple_login', 'Apple login', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa1cff36-2b13-4c3b-b9a0-fe0011356e1b', 'social_login', 'Other social login', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa1cff36-2b13-4c3b-b9a0-fe0011356e1b', 'two_factor', 'Two-factor authentication', 45, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa1cff36-2b13-4c3b-b9a0-fe0011356e1b', 'otp', 'OTP verification', 30, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa1cff36-2b13-4c3b-b9a0-fe0011356e1b', 'phone_verification', 'Phone verification', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa1cff36-2b13-4c3b-b9a0-fe0011356e1b', 'role_based_access', 'Role-based access', 45, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa1cff36-2b13-4c3b-b9a0-fe0011356e1b', 'advanced_security', 'Advanced security configuration', 60, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'aa1cff36-2b13-4c3b-b9a0-fe0011356e1b', 'security_audit', 'Security audit', 90, null, null, null, false, 10
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'b08ebdf1-53f3-49aa-9d75-025ac9753a4b', '400fb65c-a931-463f-a627-d1b0f04d8698', 'api_backend', 'integrations', 4, 'Anything this should connect to?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b08ebdf1-53f3-49aa-9d75-025ac9753a4b', 'google_services', 'Google services', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b08ebdf1-53f3-49aa-9d75-025ac9753a4b', 'google_maps', 'Google Maps', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b08ebdf1-53f3-49aa-9d75-025ac9753a4b', 'google_analytics', 'Google Analytics', 18, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b08ebdf1-53f3-49aa-9d75-025ac9753a4b', 'meta_instagram', 'Meta / Instagram', 45, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b08ebdf1-53f3-49aa-9d75-025ac9753a4b', 'tiktok', 'TikTok', 45, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b08ebdf1-53f3-49aa-9d75-025ac9753a4b', 'whatsapp_integration', 'WhatsApp', 60, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b08ebdf1-53f3-49aa-9d75-025ac9753a4b', 'mailchimp', 'Mailchimp', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b08ebdf1-53f3-49aa-9d75-025ac9753a4b', 'hubspot', 'HubSpot', 60, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b08ebdf1-53f3-49aa-9d75-025ac9753a4b', 'salesforce', 'Salesforce', 90, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b08ebdf1-53f3-49aa-9d75-025ac9753a4b', 'slack', 'Slack', 30, null, null, null, false, 10
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'b08ebdf1-53f3-49aa-9d75-025ac9753a4b', 'custom_api_integration', 'Custom API', 90, null, null, null, false, 11
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '7963d47b-f192-4de7-a8a5-6d136757f821', '400fb65c-a931-463f-a627-d1b0f04d8698', 'api_backend', 'revisions', 5, 'How many rounds of revisions do you want?', '2 rounds are included.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7963d47b-f192-4de7-a8a5-6d136757f821', 'included', '2 rounds (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7963d47b-f192-4de7-a8a5-6d136757f821', 'three', '3 rounds', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7963d47b-f192-4de7-a8a5-6d136757f821', 'four', '4 rounds', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '7963d47b-f192-4de7-a8a5-6d136757f821', 'five', '5 rounds', 60, null, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'bcc925f6-8d75-418f-911b-283239832752', '400fb65c-a931-463f-a627-d1b0f04d8698', 'api_backend', 'complexity', 6, 'How complex is this, realistically?', 'This adjusts the whole project price to reflect the extra work.', 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'bcc925f6-8d75-418f-911b-283239832752', 'standard', 'Standard — normal functionality', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'bcc925f6-8d75-418f-911b-283239832752', 'advanced', 'Advanced — more custom UI, logic, or integrations', null, 1.2, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'bcc925f6-8d75-418f-911b-283239832752', 'complex', 'Complex — substantial custom functionality, multiple integrations', null, 1.4, null, null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'dee1db45-890e-4513-a122-0c84f2531b0c', '400fb65c-a931-463f-a627-d1b0f04d8698', 'api_backend', 'delivery', 7, 'How quickly do you need it?', null, 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dee1db45-890e-4513-a122-0c84f2531b0c', 'standard', 'Standard', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dee1db45-890e-4513-a122-0c84f2531b0c', 'priority', 'Priority (+15%)', null, 1.15, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dee1db45-890e-4513-a122-0c84f2531b0c', 'rush', 'Rush (+30%)', null, 1.3, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'dee1db45-890e-4513-a122-0c84f2531b0c', 'emergency', 'Emergency (+50%)', null, 1.5, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'f7b46a1a-3b1b-4206-8a7d-136472d5d468', '400fb65c-a931-463f-a627-d1b0f04d8698', 'api_backend', 'hosting', 8, 'Do you need hosting and infrastructure set up?', null, 'multi', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'f7b46a1a-3b1b-4206-8a7d-136472d5d468', 'hosting_setup', 'Hosting setup', 30, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'f7b46a1a-3b1b-4206-8a7d-136472d5d468', 'domain_setup', 'Domain setup', 12, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'f7b46a1a-3b1b-4206-8a7d-136472d5d468', 'cdn_setup', 'CDN setup', 30, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'f7b46a1a-3b1b-4206-8a7d-136472d5d468', 'database_hosting', 'Database hosting setup', 30, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'f7b46a1a-3b1b-4206-8a7d-136472d5d468', 'file_storage_setup', 'File storage setup', 25, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'f7b46a1a-3b1b-4206-8a7d-136472d5d468', 'email_service_setup', 'Email service setup', 25, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'f7b46a1a-3b1b-4206-8a7d-136472d5d468', 'monitoring', 'Monitoring', 30, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'f7b46a1a-3b1b-4206-8a7d-136472d5d468', 'backup_system', 'Backup system', 45, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'f7b46a1a-3b1b-4206-8a7d-136472d5d468', 'production_deployment', 'Production deployment', 30, null, null, null, false, 9
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'cb0adbfb-c0b3-475a-9340-c1e94732abdc', '400fb65c-a931-463f-a627-d1b0f04d8698', 'api_backend', 'maintenance', 9, 'Want ongoing support after launch?', '30 days of post-launch support is included either way.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cb0adbfb-c0b3-475a-9340-c1e94732abdc', 'none', 'Just the 30-day post-launch support (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cb0adbfb-c0b3-475a-9340-c1e94732abdc', 'monthly', 'Monthly maintenance — €30/month', 30, null, 'per_month', null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'cb0adbfb-c0b3-475a-9340-c1e94732abdc', 'full', 'Full maintenance package — €90/month', 90, null, 'per_month', null, false, 3
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '35edc580-1b93-4e9c-8c97-1de00ced4b11', '400fb65c-a931-463f-a627-d1b0f04d8698', 'api_backend', 'custom_note', 10, 'Anything else we should know?', 'Optional. If it doesn''t fit the options above, describe it and we''ll follow up with a custom quote.', 'text', 'note', null, null, null, null, true
);
