-- Auto-generated by scripts/gen-catalogue-seed.ts from
-- apps/studio/lib/catalogue/{catalogue,shared}.ts — do not hand-edit.
--
-- published_at stays null here deliberately: catalogue_version_locked_guard
-- (20260818030000_phase7_catalogue_schema.sql) blocks writes to a published
-- version's children, so publishing before the 12 seed_NN_*.sql files below
-- have run would lock them out before they can insert. The final migration
-- in this seed sequence (20260818031012) sets is_active/published_at once
-- every project type's content is in.
insert into public.catalogue_versions (id, version_number, is_active, published_at, created_by, notes)
values ('400fb65c-a931-463f-a627-d1b0f04d8698', 1, false, null, 'system-seed', 'Initial version — mirrors the live catalogue.ts/shared.ts at Phase 7 build time.');
