-- Auto-generated by scripts/gen-catalogue-seed.ts from
-- apps/studio/lib/catalogue/{catalogue,shared}.ts — do not hand-edit.

insert into public.catalogue_project_types (version_id, type_id, label, helper, type_order, base_price)
values ('400fb65c-a931-463f-a627-d1b0f04d8698', 'branding', 'Branding', 'Logo, identity, and visual system.', 11, 120);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'a666f0ed-97f7-401b-9e27-db68821e741d', '400fb65c-a931-463f-a627-d1b0f04d8698', 'branding', 'branding_items', 1, 'What do you need?', null, 'multi', 'addon', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a666f0ed-97f7-401b-9e27-db68821e741d', 'logo_design', 'Logo design', 45, null, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a666f0ed-97f7-401b-9e27-db68821e741d', 'logo_redesign', 'Logo redesign', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a666f0ed-97f7-401b-9e27-db68821e741d', 'brand_colors', 'Brand colors', 18, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a666f0ed-97f7-401b-9e27-db68821e741d', 'typography_system', 'Typography system', 18, null, null, null, false, 4
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a666f0ed-97f7-401b-9e27-db68821e741d', 'brand_guidelines', 'Brand guidelines', 60, null, null, null, false, 5
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a666f0ed-97f7-401b-9e27-db68821e741d', 'business_card', 'Business card', 18, null, null, null, false, 6
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a666f0ed-97f7-401b-9e27-db68821e741d', 'social_kit', 'Social media kit', 45, null, null, null, false, 7
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a666f0ed-97f7-401b-9e27-db68821e741d', 'brand_assets', 'Brand assets pack', 60, null, null, null, false, 8
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a666f0ed-97f7-401b-9e27-db68821e741d', 'packaging_design', 'Packaging design', 45, null, null, null, false, 9
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'a666f0ed-97f7-401b-9e27-db68821e741d', 'full_identity', 'Full visual identity', 145, null, null, 'Everything above, bundled.', false, 10
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '45a486fd-3e7e-49e7-9852-6cbd454d1b21', '400fb65c-a931-463f-a627-d1b0f04d8698', 'branding', 'branding_style', 2, 'What style are you going for?', null, 'text', 'addon', null, null, null, null, true
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  'ead74a96-08a4-4fb6-8069-348e4d818288', '400fb65c-a931-463f-a627-d1b0f04d8698', 'branding', 'revisions', 3, 'How many rounds of revisions do you want?', '2 rounds are included.', 'single', 'addon', null, null, null, null, true
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ead74a96-08a4-4fb6-8069-348e4d818288', 'included', '2 rounds (included)', 0, null, null, null, true, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ead74a96-08a4-4fb6-8069-348e4d818288', 'three', '3 rounds', 30, null, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ead74a96-08a4-4fb6-8069-348e4d818288', 'four', '4 rounds', 45, null, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  'ead74a96-08a4-4fb6-8069-348e4d818288', 'five', '5 rounds', 60, null, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '31103045-ec69-426d-a2ee-cf5cdd183954', '400fb65c-a931-463f-a627-d1b0f04d8698', 'branding', 'delivery', 4, 'How quickly do you need it?', null, 'single', 'multiplier', null, null, null, null, false
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '31103045-ec69-426d-a2ee-cf5cdd183954', 'standard', 'Standard', null, 1, null, null, false, 1
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '31103045-ec69-426d-a2ee-cf5cdd183954', 'priority', 'Priority (+15%)', null, 1.15, null, null, false, 2
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '31103045-ec69-426d-a2ee-cf5cdd183954', 'rush', 'Rush (+30%)', null, 1.3, null, null, false, 3
);
insert into public.catalogue_options (
  step_id, option_key, label, price, multiplier, unit, description, included, option_order
) values (
  '31103045-ec69-426d-a2ee-cf5cdd183954', 'emergency', 'Emergency (+50%)', null, 1.5, null, null, false, 4
);

insert into public.catalogue_steps (
  id, version_id, project_type_id, step_key, step_order, question, helper, step_type, role, min_value, max_value, price_per_unit, included_units, optional
) values (
  '675027bf-63e4-4e72-b067-140308476dc4', '400fb65c-a931-463f-a627-d1b0f04d8698', 'branding', 'custom_note', 5, 'Anything else we should know?', 'Optional. If it doesn''t fit the options above, describe it and we''ll follow up with a custom quote.', 'text', 'note', null, null, null, null, true
);
